### ISSUE TITLE
[BUG] "Causes impersonate skin changes to need a world rejoin to show up"

### ISSUE THREAD

**Issue by TrueVenomized** [Traben-0/Entity_Texture_Features#110]
**Describe the issue**

- What happened?
   The skin does not change, but the cape and player model do (3px/4px)
- What were you doing when it happened?
   In singleplayer, run the /impersonate disguise as [any player name]
   Your player skin will not change

**Your setup: (please complete the following information):**

- Minecraft version: 1.19
- ModLoader: Fabric 0.14.9
- ETF Version: 4.1.1
- Does the issue persist with only ETF (and cloth config for forge versions) installed?
   No as without impersonate the /impersonate command does not exist

**Comment by Traben-0** [comment]
for the time being ETF skin features will get disabled for compatibility with impersonate if it is detected, this can be overridden of course, but then you'll have to return to rejoining the world for the change to take effect.

**Comment by Traben-0** [comment]
workaround implimented in release 4.2
