### ISSUE TITLE
[Suggestion] Update skin changes without needing game restart

### ISSUE THREAD

**Issue by CHEEZ-ITZ-12oz** [Traben-0/Entity_Texture_Features#112]
**Describe the issue**

- What happened?
  Skin reverts itself after a skin change
- What were you doing when it happened? [e.g. loading the game, playing multiplayer, single-player]
  Switch skin (via minecraft.net) re log single player and after a few seconds, the skin reverts. Requires a restart of Minecraft to correctly update skin.

**Your setup: (please complete the following information):**

- Minecraft version: 1.19.2
- ModLoader: Fabric
- ETF Version: 4.1.1
- The issue persists when only ETF is installed and is even worse because the skin doesn't even appear to change

**Comment by Traben-0** [comment]
Yes that is what the message says after you upload a skin, it is the current expected behaviour .

I plan to fix this eventually.
For this to work as I understand it requires the game to re authenticate the game profile, I know outed possible but have not looked into it yet.

**Comment by billyp673** [comment]
As an added note, this also means you need to relog for the skin changing effects of FabricTailor's skin changing to occur...

**Comment by Traben-0** [comment]
this has been resolved in release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0
