### ISSUE TITLE
[Suggestion] Disable vanilla emissive entities

### ISSUE THREAD

**Issue by Thanos1716** [Traben-0/Entity_Texture_Features#113]
In making a few emissive resourcepacks for this mod, I noticed more and more that Mojang have implemented their own emissive behaviour for certain mobs, here is a rough list:

- Allay
- Vex
- Blaze
- Spider eyes
- Enderman eyes
- Magma cube
- Phantom eyes
- Wither
- Beacon/end gateway beam

(There may be more but these are the ones that I noticed)
My suggestion is to add a mod setting that allows disabling this behaviour, allowing for emissive resourcepacks to work on these entities as well.
Unfortunately I am not equipped enough with Java knowledge to attempt this myself, nor to know how difficult this would be, but I think it could add some value to this amazing mod :)

**Comment by Traben-0** [comment]
For spider, endermen and phantoms eyes you can always just make the eye texture blank.

The others however are a good idea I will try and add an option

**Comment by Traben-0** [comment]
![2022-11-06_02 09 05](https://user-images.githubusercontent.com/8456487/200129256-0c236ad3-c1aa-4f81-a147-f252f24750fd.png)
It looks so strange :)

**Comment by Thanos1716** [comment]
blaze is chilly :)

**Comment by Traben-0** [comment]
Download for the dev build is in the dev blog on my discord

Documentation for the feature is in the below link on line 308

https://github.com/Traben-0/Entity_Texture_Features/blob/1.19-dev/.github/README-assets/random_entities.properties

**Comment by Traben-0** [comment]
fixed or added in release 4.2
