### ISSUE TITLE
The latest ETF crashes with Pyrotastic.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [Traben-0/Entity_Texture_Features#120]
entity_texture_features_forge_1.19.2-4.2.0 crashes Forge 1.19.2 - 43.1.52 with Pyrotastic 1.19.2+2.0.3.

[crash-2022-10-30_14.23.36-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/10026255/crash-2022-10-30_14.23.36-client.txt)

**Comment by Cr4fTJuNkiE** [comment]
That
[crash-2022-11-16_17.42.23-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/10026363/crash-2022-11-16_17.42.23-client.txt)

SORRY! Wrong Crash Log!!!! Really need to clean up my desktop!!

**Comment by Traben-0** [comment]
hmm it doesn't seem like ETF is the cause, does pyrotastic only crash with etf installed?

**Comment by Cr4fTJuNkiE** [comment]
Also does it with illuminations for Forge as well. HAs something to do with how the mods models are rendered. Does NOT happen in the 4.1.1 version of ETF. Thanks.

**Comment by Traben-0** [comment]
i'll look into this

**Comment by Cr4fTJuNkiE** [comment]
Yes, Load up the latest Forge with just ETF  4.2.0 and the latest Pyrotastic or Illuminations for forge. Crashes for me very time.

**Comment by Cr4fTJuNkiE** [comment]
Okay. Thanks! Love the mod!

**Comment by Cr4fTJuNkiE** [comment]
The new ETF 4.20.1 works great! Thanks.

**Comment by Traben-0** [comment]
I had a feeling it might fix this,  I didn't get time to test yesterday :)
