### ISSUE TITLE
[Feature] add Minecart support

### ISSUE THREAD

**Issue by I-like-Portal-2** [Traben-0/Entity_Texture_Features#122]
I'm using a [texture pack](http://phoenixsc.me/download-links/technoblade-pig-1-19/), and it should change the pig texture when named "Technoblade", but it doesn't work for some reason

![image](https://user-images.githubusercontent.com/99472757/202507602-94587a22-457f-43bb-902c-233166707c7b.png)
that's what it suppoused to look like, but it doesnt work

**Your setup: (please complete the following information):**

- Minecraft version: 1.19.2
- ModLoader: fabric
- ETF Version - 4.2.0.1
- Does the issue persist with only ETF (and cloth config for forge versions) installed? - yes

also in my resourcepack when minecart is renamed to "invisible" it becomes, well, invisible, also doesn't work, but it does with optifine

or is it a problem with cem?

**Comment by Traben-0** [comment]
it is indeed a CEM issue as the crown is a custom model

**Comment by I-like-Portal-2** [comment]
> it is indeed a CEM issue as the crown is a custom model

wait, but what about minecarts? they don't use a custom model

**Comment by Traben-0** [comment]
I don't know how minecarts are involved here,  but ETF does not yet support minecarts it is planned though

**Comment by I-like-Portal-2** [comment]
> I don't know how minecarts are involved here, but ETF does not yet support minecarts it is planned though

minecarts are involved here: 
> also in my resourcepack when minecart is renamed to "invisible" it becomes, well, invisible, also doesn't work, but it does with optifine

anyways, thank you for everything you do

**Comment by Traben-0** [comment]
Ah I see apologies I had mistook that being on another issue

**Comment by Traben-0** [comment]
this has been added in release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0
