### ISSUE TITLE
minecraft 1.18.2 keeps crashing for me when i installed this mod 

### ISSUE THREAD

**Issue by justawander** [Traben-0/Entity_Texture_Features#124]
https://pastebin.com/DVYnzHHK

**Comment by Traben-0** [comment]
Seems to be an issue with the horse armor mixin,  do you have any other mods that affect that?

**Comment by Traben-0** [comment]
I cannot replicate this myself

can you ensure you have the latest forge version for 1.18.2 and can you check if it still crashes with only ETF installed, it could be a compatibility issue with one of your mods

**Comment by 78codemonkey** [comment]
i'm on mc 1.18.2, forge 40.1.85
with tinkers latest version, i have ETF at version 4.1.1, using ETF version 4.2.0 causes compatibility crash stating
[crash-2022-12-07_19.49.38-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/10181510/crash-2022-12-07_19.49.38-client.txt). Hopefully this helps with more info and narrowing the problem :)

**Comment by 78codemonkey** [comment]
yeah, i'll test it now

**Comment by 78codemonkey** [comment]
1. Happens with opening inventory sometime, but guaranteed when opening creative inventory.
2. Disabling Tconstruct allows it to work.
3. Disabling ETF allows it to work
4. setting code to : "enableCustomBlockEntities": false, allows it to work and still render dswg eye and Tissou's Zombie Pack

**Comment by 78codemonkey** [comment]
4th option is a success and no crash :)

**Comment by Traben-0** [comment]
this has been resolved in release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0
