### ISSUE TITLE
[SUGGESTION] Add llama custom carpet texture support

### ISSUE THREAD

**Issue by Thanos1716** [Traben-0/Entity_Texture_Features#125]
Simply support the 16 different llama decor textures.
Not sure about any other mods, but Optifine does support custom entity textures for llama decor.
Perhaps the ability to link the llama decor style to the llama properties? Not sure how that would work :P

**Comment by Traben-0** [comment]
This is already included,  the color property will detect the llama carpet colour if used in llama.properties

**Comment by Traben-0** [comment]
See the documentation https://github.com/Traben-0/Entity_Texture_Features/blob/master/.github/README-assets/random_entities.properties

**Comment by Thanos1716** [comment]
Oh my apologies, but I was talking more about the custom textures than the properties, you see I have a file: assets/minecraft/optifine/random/entity/llama/decor/green2.png, which appears as a custom texture on the llama decor in Optifine, but in ETF it doesn't show up. I thought it just mustn't be implemented but maybe I'm doing something wrong? (The resourcepack folders are symlinked, so its the same pack)
Optifine:
![image](https://user-images.githubusercontent.com/80975570/202886224-55f571b0-4a7a-4a8d-be9e-aef920fcdeed.png)
ETF:
![image](https://user-images.githubusercontent.com/80975570/202886253-2d72a572-d530-4b70-9e8d-ea9b52ae7750.png)

**Comment by Traben-0** [comment]
ahh i see what you mean, yes this has not been added yet, I shall add it to the list

**Comment by Traben-0** [comment]
this has been added in release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0
