### ISSUE TITLE
[BUG] Emissive Textures Don't Work With 3d Skin Layers

### ISSUE THREAD

**Issue by TrueVenomized** [Traben-0/Entity_Texture_Features#128]
**Describe the issue**
While testing an ETF skin I was making for someone, I found that when using the 3d Skin Layers mod, emissive player skins aren't emissive on the 3d layers (i.e. the outer layer)
I have also submitted an issue on the 3d Skin Layers Github
3d Skin Layers Github: https://github.com/tr7zw/3d-Skin-Layers

**Screenshots**
(I'm using shaders because it makes the emissive textures more visible)
With 3d Skin Layers
![2022-12-21_19 33 57](https://user-images.githubusercontent.com/86860005/209029881-1be2c082-9402-4569-8c91-0b2eed385af4.png)
Without 3d Skin Layers
![2022-12-21_19 34 22](https://user-images.githubusercontent.com/86860005/209029882-7cba803b-875e-4992-b909-fa4a8789b29f.png)

**Your setup: (please complete the following information):**

- Minecraft version: 1.19.2
- ModLoader: Fabric
- ETF Version: 4.2.0
- Does the issue persist with only ETF installed?
     No, as the issue is caused by the mod
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?
     Yes

**Comment by Traben-0** [comment]
This is a known incompatibility, it would take a lot of work to make compatible, so will remain incompatible for a while if not always :(

**Comment by Traben-0** [comment]
https://github.com/tr7zw/3d-Skin-Layers/issues/93#issuecomment-1362261425 leaving this here for my own reference tomorrow

**Comment by Traben-0** [comment]
Dev build in my discord with the first pass of the fix for fabric

**Comment by Traben-0** [comment]
this has been resolved in release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0
