### ISSUE TITLE
[BUG] Broken texture paths option does the opposite

### ISSUE THREAD

**Issue by Madis0** [Traben-0/Entity_Texture_Features#129]
**Describe the issue**

- What happened? The option "allow broken texture paths" prevents resource packs with broken paths from being loaded, aka the error will be logged and all resource packs will be disabled.
- What were you doing when it happened? Enabling resource packs that have broken paths 

**Screenshots**

N/A

**Crash log**

https://mclo.gs/mtcTZPC
https://mclo.gs/vyGm5s2

**Your setup: (please complete the following information):**

- Minecraft version: 1.19.3
- ModLoader: Fabric
- ETF Version 4.2.0.1
- Does the issue persist with only ETF installed? Not tested yet
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? Yes

See also:

https://discord.com/channels/859124104644788234/859124571005648946/1056922668764508240
https://discord.com/channels/859124104644788234/859124571005648946/1054991864161374269

**Comment by Traben-0** [comment]
I was made aware of this a short while ago, in the cases I have seen it is a failing of the allow broken paths fix to account for .mcmeta files, the code for which has changed in 1.19.3 to allow a crash, I should have a fix out tomorrow as it is late now. 

In the mean time disabling the illegal texture path setting is recommended and will prevent crashes.

**Comment by Traben-0** [comment]
this has been resolved in release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0
