### ISSUE TITLE
[BUG] Ghosts resource pack issue

### ISSUE THREAD

**Issue by EGOIST1372** [Traben-0/Entity_Texture_Features#134]
**Describe the issue**

Crashes in 1.19.3 while flying fast in creative mode in single player

**Crash log**

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2023-01-13 04:20:30
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.method_12832()" because "variantIdentifier" is null
	at traben.entity_texture_features.texture_handlers.ETFTexture.<init>(ETFTexture.java:69)
	at traben.entity_texture_features.texture_handlers.ETFManager.getOrCreateETFTexture(ETFManager.java:517)
	at traben.entity_texture_features.texture_handlers.ETFManager.getETFDefaultTexture(ETFManager.java:209)
	at traben.entity_texture_features.texture_handlers.ETFManager.getETFTexture(ETFManager.java:304)
	at net.minecraft.class_881.handler$bab000$etf$applyEmissive(class_881.java:607)
	at net.minecraft.class_881.method_3888(class_881.java:96)
	at net.minecraft.class_881.method_3936(class_881.java:28)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at traben.entity_texture_features.texture_handlers.ETFTexture.<init>(ETFTexture.java:69)
	at traben.entity_texture_features.texture_handlers.ETFManager.getOrCreateETFTexture(ETFManager.java:517)
	at traben.entity_texture_features.texture_handlers.ETFManager.getETFDefaultTexture(ETFManager.java:209)
	at traben.entity_texture_features.texture_handlers.ETFManager.getETFTexture(ETFManager.java:304)
	at net.minecraft.class_881.handler$bab000$etf$applyEmissive(class_881.java:607)
	at net.minecraft.class_881.method_3888(class_881.java:96)
	at net.minecraft.class_881.method_3936(class_881.java:28)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
Mixins in Stacktrace: None found

-- Entity being rendered --
Details:
	Entity Type: minecraft:boat (net.minecraft.class_1690)
	Entity ID: 24
	Entity Name: Boat
	Entity's Exact location: 168.69, 62.52, -107.31
	Entity's Block location: World: (168,62,-108), Section: (at 8,14,4 in 10,3,-7; chunk contains blocks 160,-64,-112 to 175,319,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace: None found

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_881@1b73fb8d
	Location: -63.70,-29.00,-37.70 - World: (-64,-30,-38), Section: (at 0,2,10 in -4,-2,-3; chunk contains blocks -64,-64,-48 to -49,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Rotation: 168.75
	Delta: 0.6200526
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace: None found

-- Affected level --
Details:
	All players: 1 total; [class_746[''/137, l='ClientLevel', x=231.98, y=89.91, z=-69.58]]
	Chunk stats: 1024, 618
	Level dimension: minecraft:overworld
	Level spawn location: World: (144,64,-192), Section: (at 0,0,0 in 9,4,-12; chunk contains blocks 144,-64,-192 to 159,319,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 2170709 game time, 332292 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:800)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace: None found

-- Last reload --
Details:
	Reload number: 3
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, file/VIllagerAndOthersCloakFix.zip, file/Butterflies+-+Mrblueyeti.zip, file/Boss+Bars++1.18+Update.zip, file/Desert_Bloom-v1.0.2.zip, file/Luminous1.3.zip, file/itemframes-e700.zip, file/Flower_Crowns_(1.18)_v2.zip, file/Flower_Golems_v1.zip, file/Kubban's Saplings, Fabric Mods, itemswapper/default, file/Better_Chickens_V1.3.zip, file/Better+sheep+-+Mrblueyeti.zip, file/Better_Cats_V0.05.zip, file/Better_Dogs-Shiba_Inu.zip, file/Ghosts.zip, file/VanillaTweaks_1.19.3.zip, loadmyresources.hiddenpack, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1640188432 bytes (1564 MiB) / 2818572288 bytes (2688 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 980M
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1617
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37310.99
	Virtual memory used (MB): 28101.08
	Swap memory total (MB): 4607.14
	Swap memory used (MB): 634.54
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.3-fabric0.68.1-1.3.1
		ambientenvironment: Ambient Environment 8.0+4
		architectury: Architectury 7.0.66
		armorchroma: Armor Chroma 1.2.4
		audioplayer: AudioPlayer 1.19.3-1.4.5
		auudio: Auudio 1.0.3
		bettermounthud: Better Mount HUD 1.2.1
		biomeinfo: BiomeInfo 1.19.2-12
		blur: Blur (Fabric) 2.6.1
		bookshelf: Bookshelf 17.0.3
		camerautils: Camera Utils 1.19.3-1.0.3
		cem: Custom Entity Models 0.7.1
		chalk: Chalk 2.1.1
		chalk-colorful-addon: Chalk: Colorful-Addon 2.1.1+1.19.3
		chat_heads: Chat Heads 0.9.0
		chime: Chime 1.4.0
		chisel: Chisel Refabricated 1.4.5
			continuity: Continuity 2.0.2+1.19.3-build.2
		citresewn: CIT Resewn 1.1.3+1.19.3
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.3
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+16
		collective: Collective 6.22
			collective-fabric: Collective (Fabric) 5.50
				fiber: fiber 0.23.0-2
		completeconfig: CompleteConfig 2.2.1
			coat: Coat 1.0.0-beta.19+mc1.19.3
			completeconfig-base: completeconfig-base 2.2.1
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.1
			completeconfig-gui-coat: completeconfig-gui-coat 2.2.1
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.2.1
		configured: Configured 2.0.2
		controlling: Controlling For Fabric 10.0+9
		creativeonepunch: Creative One-Punch 1.3
		cyclepaintings: Cycle Paintings 3.0
		darkpaintings: DarkPaintings 14.0.1
		dashloader: DashLoader 5.0.0-alpha.6+1.19.3
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.2
			dev_quantumfusion_taski: Taski 2.1.0
		deathlog: DeathLog 0.3.0+1.19.3
		drippyloadingscreen: Drippy Loading Screen 1.6.6
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		entity_texture_features: Entity Texture Features 4.3.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19.3
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		exordium: Exordium 1.0.3-mc1.19.3
		extrasounds: ExtraSounds 2.3.1+1.19.3~lonefelidae16-SNAPSHOT
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			soundcategories: Sound Categories 1.2.4+1.19.3~lonefelidae16-SNAPSHOT
		fabric-api: Fabric API 0.72.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.0+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.11+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.21+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.38+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.46+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.4+1134c5b885
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.39+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.42+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.8+1134c5b885
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.11+1134c5b885
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.30+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.28+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.16+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.33+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.3.0+85f102ee85
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.4+1134c5b885
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.0+9f179aa185
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+9f179aa185
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+6dc0edd785
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.2+1134c5b885
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.12+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.14+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.0+5b9a588b85
		fabricloader: Fabric Loader 0.14.12
		fallingleaves: Falling Leaves 1.14.3+1.19.3
		fancymenu: FancyMenu 2.13.2
		fastopenlinksandfolders: FastOpenResourcePacks 1.1.1
		ferritecore: FerriteCore 5.1.0
		fmextension_audio: FancyMenu Audio Extension 1.1.1
		forgeconfigapiport: Forge Config API Port 5.0.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		fpsdisplay: FPS-Display 1.5.0+1.19
		freecam: Freecam 1.1.8+1.19
		image2map: Image2Map 0.4.0
			map-canvas-api: Map Canvas API 0.2.1+1.19.3
			sgui: sgui 1.2.0+1.19.3
		immediatelyfast: ImmediatelyFast 1.1.6
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		impactfulweather: Biome Particle Weather 4.0.4
		indium: Indium 1.0.12+mc1.19.3
		inventoryhud: Inventory HUD + 3.4.7
		iris: Iris 1.5.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemswapper: ItemSwapper 0.3.2-mc1.19.3
		java: OpenJDK 64-Bit Server VM 17
		keepheadnames: Keep Head Names 1.5.1
		konkrete: Konkrete 1.6.0
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lightoverlay: Light Overlay 7.0.2
		lithium: Lithium 0.10.4
		loadmyresources: Load My Resources 1.0.4
		malilib: MaLiLib 0.14.0
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		microdurability: microDurability 0.3.6+1.19
			microdurability-core: microDurability Core 0.3.6
		midnightlib: MidnightLib 1.1.0
		minecraft: Minecraft 1.19.3
		minihud: MiniHUD 0.25.0
		mixintrace: MixinTrace 1.1.1+1.17
		modmenu: Mod Menu 5.0.2
		multibeds: MultiBeds 1.3.3
		nicephore: Nicephore fabric-1.19.x-1.0.0
			com_profesorfalken_jpowershell: jPowerShell 3.1.1
		notenoughanimations: NotEnoughAnimations 1.6.2
		onsoulfire: On Soul Fire 1.19-3
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
		owo: oωo 0.9.3+1.19.3
			blue_endless_jankson: jankson 1.2.1
		phosphor: Phosphor 0.8.1
		presencefootsteps: Presence Footsteps 1.7.1
			kirin: Kirin UI 1.13.2
		puzzle: Puzzle 1.4.2-1.19.3
			puzzle-base: Puzzle Base 1.4.2-1.19.3
			puzzle-gui: Puzzle GUI 1.4.2-1.19.3
			puzzle-models: Puzzle Models 1.4.2-1.19.3
			puzzle-splashscreen: Puzzle Splash Screen 1.4.2-1.19.3
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		replaymod: Replay Mod 1.19.3-2.6.10
		replayvoicechat: Replay Voice Chat 1.19.3-1.2.4
		roughlyenoughitems: Roughly Enough Items 10.0.581
			error_notifier: Error Notifier 1.0.9
		satin: Satin 1.10.0
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		searchlight: Searchlight 1.1.9
		shetiphiancore: ShetiPhianCore 1.3.5
		showmeyourskin: Show Me Your Skin! 1.3.7+1.19.3
			cicada: CICADA 0.1.1
				langfiles-plus: Langfiles Plus 1.0.0
		shulkerboxtooltip: Shulker Box Tooltip 3.2.4+1.19.3
		silence: Silence 1.19.3-fabric0.68.1-1.0.1
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.3
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.8+build.22
		sodium-extra: Sodium Extra 0.4.16+mc1.19.3-build.91
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19.3-1.0.18
		status: Status 1.19.3-1.0.0
		status-effect-bars: Status Effect Bars 1.0.2
		stendhal: Stendhal 1.3.4-1.19.3
			libgui: LibGui 6.5.0+1.19.3
				jankson: Jankson 5.0.0+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		vcinteraction: Voice Chat Interaction 1.19.3-1.0.3
			polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.3.0-rc.3+1.19.3
		voicechat: Simple Voice Chat 1.19.3-2.3.26
		waveycapes: WaveyCapes 1.2.2
		wi_zoom: WI Zoom 1.4-MC1.19.3
		windchimes: Windchimes 1.2.2
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.12-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 980M/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.29, NVIDIA Corporation
	Window size: 3840x2160
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/VIllagerAndOthersCloakFix.zip (incompatible), file/Butterflies+-+Mrblueyeti.zip (incompatible), file/Boss+Bars++1.18+Update.zip (incompatible), file/Desert_Bloom-v1.0.2.zip (incompatible), file/Luminous1.3.zip (incompatible), file/itemframes-e700.zip (incompatible), file/Flower_Crowns_(1.18)_v2.zip (incompatible), file/Flower_Golems_v1.zip (incompatible), file/Kubban's Saplings (incompatible), fabric, itemswapper:default, file/Better_Chickens_V1.3.zip (incompatible), file/Better+sheep+-+Mrblueyeti.zip (incompatible), file/Better_Cats_V0.05.zip (incompatible), file/Better_Dogs-Shiba_Inu.zip (incompatible), file/Ghosts.zip (incompatible), file/VanillaTweaks_1.19.3.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222[''/137, l='ServerLevel[test 1.17]', x=231.98, y=89.91, z=-69.58]]
	Data Packs: vanilla, loadmyresources.hiddenpack (incompatible), fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Your setup: (please complete the following information):**

- Minecraft version: 1.19.3
- ModLoader: fabric latest
- ETF Version: entity_texture_features_fabric_1.19.3-4.3.1

**Comment by Traben-0** [comment]
I will look into this, does it still happen with only ETF installed

**Comment by EGOIST1372** [comment]
I can't say for sure since I believe a combination on mods triggered it

**Comment by EGOIST1372** [comment]
and it seems I can't enter that world anymore it insta crashes
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.method_12832()" because "variantIdentifier" is null
same error
maybe it's because of new resource pack I got? [Ghosts](https://www.curseforge.com/minecraft/texture-packs/ghosts/files)

**Comment by eithli** [comment]
Different resource pack, but I can confirm the same issue. I found that when "random mobs" were turned off, the game would crash when boats were rendered. (1.19.3)

**Comment by Traben-0** [comment]
Interesting, must be an issue that slipped past my testing cause I had the setteing enabled

**Comment by EGOIST1372** [comment]
@Traben-0 I didn't want to create a new issue for this so I'm telling it here
your random mob option in puzzle menu can be disabled(you can turn it off)
but for turning it on, it just doesn't work
you need to do it from ETF's own setting to turn it on and it won't turn on in puzzle's menu

**Comment by Traben-0** [comment]
this should be fixed with dev build 4.3.2.dev.2 available in my discord can you confirm?

as for the puzzle issue I have updated the api to provide a better getter for the ETFConfig, which should fix this, I will loook into PRing puzzle to support a fix once everything is out

**Comment by Traben-0** [comment]
marking as fixed in release 4.3.2, please reopen if you run into it again, i'm pretty certain It shoudn't happen again
