### ISSUE TITLE
EFT seems to be incompatibility with quark for 1.18.2

### ISSUE THREAD

**Issue by maximal500** [Traben-0/Entity_Texture_Features#136]
i recently unloaded all my mods to figure out which one doesn't work with EFT and it seems to be quark as when ever i have the two installed the game crashes while loading

https://pastebin.com/2DD1sM58

- Minecraft version: 1.18.2
- ModLoader: forge
- ETF Version 4.3.1

**Comment by Traben-0** [comment]
are you certain ETF is the cause, it seems to be a crash related to AutoRegLib

**Comment by Traben-0** [comment]
java.lang.ClassNotFoundException: vazkii.arl.item.BasicItem

**Comment by Traben-0** [comment]
this should not at all be something triggered by etf as it never calls such a class, I will look into it further when i get time

**Comment by KarinMiku** [comment]
i was able to play with quark + the latest version of ETF, even without disabling the animal texures from quark, and also with an old version like 3.1.5 (which is the one im currently using) and they work well together so idk, i doubt it is cuz of quark

**Comment by Traben-0** [comment]
which of your mods needs AutoRegLib?

**Comment by Traben-0** [comment]
were you able to identify this issue further? 

I am quite certain it is not an ETF issue, it seems to be an issue with incorrect or missing versions of AutoRegLib
