### ISSUE TITLE
[SUGGESTION] Skin transparency / Other skin features always active without marker

### ISSUE THREAD

**Issue by Brancieq-Paul** [Traben-0/Entity_Texture_Features#142]
Currently, the mod only renders skins features for others players if these players previously set the markers on their skins.

It could be great to be able to force enable these features, independently or not.

For example, some players made transparent skins with other mods that don't need the marker, and I would like to be able to force the skin transparency enabled even if the skins don't have the marker.

**Comment by Traben-0** [comment]
I will add this as an option

**Comment by Traben-0** [comment]
this has been added with dev build 4.3.2.dev.2 available in my discord could you give it a test?

**Comment by Traben-0** [comment]
added in release 4.3.2
