### ISSUE TITLE
[SUGGESTION] "Custom Entity Models"

### ISSUE THREAD

**Issue by WuschelWookie** [Traben-0/Entity_Texture_Features#143]
Hey, I was using optifine just a few weeks ago. But it wouldnt work with some of the mods I play with, so I switched to Rubidium and Oculus. Both are some sort of Sodium port for forge. It worked great but some of the texture packs didnt work anymore. Well, and thats the reason I was so happy to stumble upon your mod, because it can solve these texture pack issues. Now the problem is, I would also need the "Custom Entity Models mod" because I think this texture pack also changes the model of some mobs like bats or animal children. But this mod only works for fabric, right? So I was wondering if you could help me with this question or not.

The name of the texture pack is Creature Variety (https://www.planetminecraft.com/texture-pack/creature-variety-pack-random-mobs-4339437/). If you could look at the pictures the owner provides, you can see the animal children and squids. So please just tell me if there is any chance to implement this with you mod ^^

**Comment by Traben-0** [comment]
i'm working on a seperate mod for this

fabric dev builds are on my discord https://discord.gg/jjSup4H8

a forge version will come when its ready

**Comment by WuschelWookie** [comment]
okay, thanks for answering ^^

**Comment by Pilogoude** [comment]
If Fresh Animations work it will be the best day of my life !

**Comment by Traben-0** [comment]
it "mostly" does already, still a few kinks to iron out though

**Comment by Traben-0** [comment]
https://modrinth.com/mod/entity-model-features :)
