### ISSUE TITLE
[BUG] Need mod for all players on Essential server

### ISSUE THREAD

**Issue by Pilogoude** [Traben-0/Entity_Texture_Features#144]
If a player invites another player on his world with Essential, the other players will need the Entity Texture Features mod otherwise an error is displayed (problem not present on a non Essential server)

![image](https://user-images.githubusercontent.com/109528004/218338689-9ebb6101-edff-4bf2-8ef5-76bcb40dcc04.png)

- Minecraft version: 1.19.3
- ModLoader: Fabric
- ETF Version 4.3.1
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue ? No ._.'

**Comment by Traben-0** [comment]
Hmm, I will look into this

**Comment by Pilogoude** [comment]
Glad I could help for ETF 4.3.2

**Comment by Traben-0** [comment]
perfect timing, 

this should be fixed with dev build 4.3.2.dev.2 available in my discord now, can you confirm?

**Comment by Pilogoude** [comment]
Sure, I'll try it when my friend is online.

**Comment by Pilogoude** [comment]
He has the mod, I dont, I join it with essential without problem, the fix works.

**Comment by Traben-0** [comment]
fixed in release 4.3.2
