### ISSUE TITLE
[BUG] missing textures

### ISSUE THREAD

**Issue by 4ll4b0v3** [Traben-0/Entity_Texture_Features#145]
i was checking to see if mobs work since it used to be invisible, they now are visible but some are missing textures

- Minecraft version: [1.19.3]
- ModLoader: [quilt]
- ETF Version [4.3.1]
- yes
- yes
![image](https://user-images.githubusercontent.com/125520509/219228848-bdaf26b5-47ec-4612-b448-c89e98c2c638.png)

**Comment by Traben-0** [comment]
Do you have any messages in your log mentioning missing textures, it's possible you have a properties file pointing to non existent textures

**Comment by bluegreensea** [comment]
Seems to be a conflicting issue with Sodium 0.4.9

**Comment by Traben-0** [comment]
What is the conflict, can I see. your mod list and reaourcepack,  cem also has a new version that is required for the latest sodium

**Comment by bluegreensea** [comment]
- cem-0.7.2.jar
- CITResewn-1.1.3+1.19.3.jar
- entity_texture_features_fabric_1.19.3-4.3.1.jar
- fabric-api-0.73.2+1.19.3.jar
- sodium-fabric-mc1.19.3-0.4.9+build.23.jar / 0.4.8 / not install

[test.zip](https://github.com/Traben-0/Entity_Texture_Features/files/10775965/test.zip)
This resource pack works with Sodium 0.4.8 installed or not installed, but not with 0.4.9.
I don't know it's a etf or cem problem.

**Comment by Traben-0** [comment]
okay this is a resourcepack with only a skeleton model, is this pack having the same issue as your first screenshot?

**Comment by bluegreensea** [comment]
I'm not the same one, just guessing what happened to 4ll4b0v3.
Here is a screenshot when installed sodium 0.4.9.
![image](https://user-images.githubusercontent.com/35960465/219923518-53dfd8b4-9984-4804-b772-9888468428aa.png)

**Comment by Traben-0** [comment]
I did not realise you weren't the original poster can you make a seperate issue and I will look into this, its possible these are unrelated issues

**Comment by bluegreensea** [comment]
Okay, I realize this is a cem bug, even though cem 0.7.2 says it fixes compatibility with sodium.
I'll open a new issue there.
thanks.

**Comment by Traben-0** [comment]
@4ll4b0v3 were you able to resolve this? 
are you using the latest sodium and CEM?

can i have the resourcepack you were having issues with
