### ISSUE TITLE
[BUG] Armor stand Marker:1b not work

### ISSUE THREAD

**Issue by bluegreensea** [Traben-0/Entity_Texture_Features#149]
- armorstand/wood.properties not work for armor stand when set Marker:1b

**Screenshots**

![image](https://user-images.githubusercontent.com/35960465/222641409-18dd5950-2939-4c73-89fd-52c127ebdd1f.png)

- Minecraft version: [1.19.3]
- ModLoader: [fabric]
- ETF Version [4.3.3.dev.1]
- Does the issue persist with only ETF installed? [yes]
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? [yes]

[test.zip](https://github.com/Traben-0/Entity_Texture_Features/files/10878622/test.zip)

**Comment by Traben-0** [comment]
any messages in the log?

**Comment by bluegreensea** [comment]
no, except info message

**Comment by bluegreensea** [comment]
fixed in release 4.3.5
