### ISSUE TITLE
[BUG or NEW FEATURE?] "vanillaBrightnessOverride and entityRenderLayerOverride for one type horse work on all type horses"

### ISSUE THREAD

**Issue by YoungSoulluoS** [Traben-0/Entity_Texture_Features#156]
Good afternoon. 
Making a texture pack with transparent textures. 
I specify only for black, but it works for all types of horses. 

entity_texture_features_fabric_1.19.4-4.3.5

BLACK
skins.2=2
entityRenderLayerOverride=translucent
vanillaBrightnessOverride=15
nbt.2.NoAI=exists:true

WHITE
skins.2=2
nbt.2.NoAI=exists:true

![image](https://user-images.githubusercontent.com/70120313/229480038-e0505c4a-0a1f-4f6a-9479-5dd747d6faba.png)
![image](https://user-images.githubusercontent.com/70120313/229479724-f7810d72-71ea-41fc-b469-3df5b43d92c4.png)
![image](https://user-images.githubusercontent.com/70120313/229481235-9c671632-8c86-4084-9edd-75930046991d.png)

**Comment by YoungSoulluoS** [comment]
Well I understood the logic that these effects apply to the horse model.
And I solved it by using emissive texture for each type horse individually.

Do I close the ticket or does it really make sense?

**Comment by Traben-0** [comment]
Yeah as it works now it applies to the entire entity type, hence why they do not have a number in the property name 

I may consider changing it to be per variant but that will be a bit if s rework of it
