### ISSUE TITLE
[SUGGESTION] Player Skin Features should show up in Player Head block

### ISSUE THREAD

**Issue by GhostIsBeHere** [Traben-0/Entity_Texture_Features#157]
My emissive and enchanted skin features are not applied to the "player_head" item or block, and I would like them to be! If this is possible with just ETF, great! If not, I'll also open a suggestion in Continuity

**Screenshots** 
Without Nightvision
![Without Nightvision](https://user-images.githubusercontent.com/61166139/230487273-b73d6b1f-1b40-4893-8135-cfe9d9e6deca.png)
With Nightvision
![With Nightvision](https://user-images.githubusercontent.com/61166139/230487475-e7d50e45-00a9-41a0-b55d-f8cb7f019cf0.png)

**Comment by Traben-0** [comment]
I'll look into it,  it should be possible

**Comment by Traben-0** [comment]
![2023-04-15_14 58 16](https://user-images.githubusercontent.com/8456487/232183949-d69ea926-f1ce-4805-9ae9-1de1f52aa950.png)
:)

**Comment by Traben-0** [comment]
Added in 4.4
