### ISSUE TITLE
Cats and Wolves change skin after being tamed

### ISSUE THREAD

**Issue by Tapacywka** [Traben-0/Entity_Texture_Features#160]
![image](https://user-images.githubusercontent.com/71761232/232345736-214a322f-8490-46a3-9741-ed5674406550.png)
When using this option, Cats and Wolves during taming in 8/10 cases change their skin to random.
I'm using Minecraft 1.19.4, Quilt Loader 0.18.10, entity_texture_features_fabric_1.19.4-4.4.0-dev.1.jar and PureBDcraft 32x rpack.
For example: I have three wolf skins (white, brown and black). After I tame a black wolf, it becomes either white or black; white becomes black or brown, and brown becomes white or black. As I wrote earlier, this does not always work, sometimes he still retains his skin after taming.

**Comment by Traben-0** [comment]
Are there the exact same number of texture variants for wild and tamed wolves? And do they number up exactly,  like is the brown one number 2 for both?

**Comment by Traben-0** [comment]
I think I see the issue, copy wolf.properties and name it wolf_tame.properties for now

**Comment by Traben-0** [comment]
Fixed in 4.4
