### ISSUE TITLE
[BUG] 'not' modifier does not work

### ISSUE THREAD

**Issue by RyanCR03** [Traben-0/Entity_Texture_Features#161]
**Describe the issue**

using the '!' modifier on a random entity parameter does not work
I have a section in my resourcepack that has:
`biomes.3=!the_void the_end deep_dark end_barrens end_highlands end_midlands small_end_islands nether_wastes basalt_deltas soul_sand_valley crimson_forest warped_forest lush_caves !dripstone_caves !badlands badlands_plateau modified_badlands_plateau wooded_badlands_plateau modified_wooded_badlands_plateau eroded_badlands`
the intended behavior is to only show the specific texture if the entity is not in the specified biomes.

**Your setup: (please complete the following information):**

- Minecraft version: 1.19.4
- ModLoader: Quilt
- ETF Version 4.3.5
- Does the issue persist with only ETF installed? Yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? Yes

**Comment by Traben-0** [comment]
I will look into this if they aren't working, as a matter of fact I have redone this code in 4.4.0.dev.1 available in my discord,  I recommend you try it out. 

 however are you sure this is what you want your properties to look like?

Nots are really only useful by themselves,  as there is no difference between

Biomes= forest !desert
And
Biomes=forest

Which I think applies to your example

**Comment by RyanCR03** [comment]
yes that is the same way it works in optifine. I originally thought the '!' only applied to the items that you put it in front of, but after further testing, i think the mod is trying to find a biome name with the '!' in front.

**Comment by Traben-0** [comment]
Fixed in 4.4
