### ISSUE TITLE
[BUG] Broken 3D Skin Layers when using Emotecraft emotes with bend

### ISSUE THREAD

**Issue by TheCatRiX** [Traben-0/Entity_Texture_Features#165]
**Describe the issue:**

- When I'm using Emotecraft emote with bend (for example [SPE_ModelPose.zip](https://github.com/Traben-0/Entity_Texture_Features/files/11312249/SPE_ModelPose.zip)), 3D layers are broken. It seems to be because of the ETF's Player skin feature, but disabling it doesn't help.
<details>
<summary>Screenshot</summary>
 
[![Screenshot][1]][1]
 
[1]: https://user-images.githubusercontent.com/58901923/234047876-d09d897e-75e4-4589-94a5-50c84d7585ba.png
 
</details>

**My setup:**

- Minecraft version: 1.19.4
- ModLoader: Quilt
- ETF Version: 4.4.0
- Does the issue persist with only ETF installed? No
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? Yes

<details>
<summary>Mods</summary>
 
[![Mods folder][2]][2][![Mod Menu][3]][3]
 
[2]: https://user-images.githubusercontent.com/58901923/234049081-b7d91de0-0070-43f2-b30e-0e2c08db156f.png
[3]: https://user-images.githubusercontent.com/58901923/234049314-9015df6a-4f04-475b-a378-7698baf5a8f9.png
 
</details>

**Comment by JonnyBro** [comment]
I don't think thats a ETF problem

**Comment by TheCatRiX** [comment]
But without ETF it works fine

**Comment by JonnyBro** [comment]
Hm, it is, strange

**Comment by Traben-0** [comment]
It's possible my 3d skin layer changes break some kind of compatibility meant for them

**Comment by TheCatRiX** [comment]
Can you please add bending support or make this togglable for compatibility

**Comment by Traben-0** [comment]
I will see what I can do, I can certainly make it toggleable

**Comment by TheCatRiX** [comment]
Tested on 4.4.2-dev. After disabling 3D skin layers mod patch and restarting game it works properly
<details>
<summary>Screenshot</summary>
 
[![Screenshot][1]][1]
 
[1]: https://user-images.githubusercontent.com/58901923/237028112-99ea85e1-b78c-49d5-9a38-3341706ee28c.png
 
</details>

**Comment by Traben-0** [comment]
that is good to hear :)

**Comment by Traben-0** [comment]
Added the config option in 4.4.3

**Comment by Stilmert** [comment]
I don't understand how you did it. Can you please explain how

**Comment by TheCatRiX** [comment]
What do you mean? Explain what? Please, provide more information. Do you have similar issue?

**Comment by Stilmert** [comment]
I also have a problem with emotecraft and 3dlayerskins the same as yours

**Comment by TheCatRiX** [comment]
Mod versions? Any other mods installed? Does the issue persist without ETF installed?

**Comment by Stilmert** [comment]
emotecraft - 2.4.0
skinlayers3d - 1.6.4
without ETF - don't work

**Comment by Stilmert** [comment]
You said that you fixed it, can you tell me how?

**Comment by Stilmert** [comment]
i download 0.5.5 its too don't work

**Comment by TheCatRiX** [comment]
Provide full list of mods (screenshot of mods folder)

**Comment by Stilmert** [comment]
![2024-05-09_13-47-19](https://github.com/Traben-0/Entity_Texture_Features/assets/148045834/b470da42-1aaf-4f79-85d0-9130cb595dde)
all mods are here, I deleted all mods except emotecraft, sodium, indium, skinlayers3d and it still didn't work

**Comment by TheCatRiX** [comment]
ahh, I forgot, there is also an [issue](https://github.com/KosmX/emotes/issues/451) in 3dskinlayers 1.6.0 and newer. I'm playing on 1.20.1 so I just downgraded to 1.5.4 but for 1.20.4 there is no older versions

**Comment by Stilmert** [comment]
aaaaaah so that's the problem okay thanks for telling me!

**Comment by Voy222** [comment]
![Image](https://github.com/user-attachments/assets/2ca6e156-c03c-4b4d-b224-b83c372cc052)
I did everything as you wrote, but nothing helped. What do you think?

**Comment by theGloomy123** [comment]
maybe I was just lucky, but I was able to solve the problem. You need to go to the 3d skin layers mod settings and enable compatibility mode.

![Image](https://github.com/user-attachments/assets/b324cfd7-0552-434c-a82d-a7e6eeb7ee7b)

**Comment by Jotamer** [comment]
Hi, I'm having the same issue, i activated Compatibility Mode and it doesn't work fully, everything works excepting the legs and torso
i would really like to know if t here's a fix to this

![Image](https://github.com/user-attachments/assets/5d3e1579-868b-4a6b-ba7e-74a5ed7ffdd4)

**Comment by Sigmayapril** [comment]
> maybe I was just lucky, but I was able to solve the problem. You need to go to the 3d skin layers mod settings and enable compatibility mode.
> 
> ![Image](https://github.com/user-attachments/assets/b324cfd7-0552-434c-a82d-a7e6eeb7ee7b)

i cant..
