### ISSUE TITLE
[SUGGESTION] Random textures for creeper armor (charge aura)

### ISSUE THREAD

**Issue by Vladomeme** [Traben-0/Entity_Texture_Features#168]
Optifine allows setting random/custom textures for creeper's charged effect (creeper_armor.properties) 
![image](https://user-images.githubusercontent.com/84517135/236671300-08358837-1133-479b-a7f6-843708ff3cb4.png)
Would be nice to have that feature in ETF, since now you can only have the default armor texture
![image](https://user-images.githubusercontent.com/84517135/236671841-9b787809-135f-49ff-bba4-28ac027eb1f7.png)

**Comment by Traben-0** [comment]
Added in 4.4.3
