### ISSUE TITLE
[BUG] Critical injection failure: `MixinCreeperEnergySwirlFeatureRenderer`

### ISSUE THREAD

**Issue by zndrmn** [Traben-0/Entity_Texture_Features#170]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

- What happened? [Tried to load minecraft and it didn't]
- What were you doing when it happened? [Loading the game and stilling in my chair patiently]

**Screenshots**

- If applicable, add screenshots to help explain your problem.

**Crash log**

- If the issue is a crash you **must** provide a crash log or nothing can be done.
- If it is not a crash your latest.log is always helpful to diagnose potential issues.
- https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report

[**latest.log**](https://gist.github.com/zndrmn/0b0cd02085b1e3eb7afe620140d91b36#file-latest-log)
_Crash log wasn't created_

**Your setup: (please complete the following information):**

- Minecraft version: [1.19.3]
- ModLoader: [fabric]
- ETF Version [4.4.3]
- Does the issue persist with only ETF installed?
yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?
yes

**Comment by Traben-0** [comment]
hmm i thought that was only a forge issue when i tested it there will be a fix up soon

**Comment by Traben-0** [comment]
4.4.4 should fix this
