### ISSUE TITLE
MinecraftCapes changing API URL

### ISSUE THREAD

**Issue by james090500** [Traben-0/Entity_Texture_Features#173]
Our API endpoints are changing soon. 

Old: `https://minecraftcapes.net/profile/{uuid}`
New: `https://api.minecraftcapes.net/profile/{uuid}`

The 'new' api is live now and will work the same as the old. I wont be turning off the old api for some months so just trying to get ahead of the curve.

**Comment by Traben-0** [comment]
thanks for the heads up

**Comment by Traben-0** [comment]
resolved in version 4.5.0
