### ISSUE TITLE
[BUG] Weird texure sizing for Random entitities

### ISSUE THREAD

**Issue by LadyHaley** [Traben-0/Entity_Texture_Features#174]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

Using the resource pack https://www.curseforge.com/minecraft/texture-packs/newdefaultplus
some of the entities within the random file structure dont behave as they would on optifine.
I beleive the issue is caused by unexpected an texture size. I have noticed the affected textures are not the same scale as the default texture, so it does some form of scaling of the texture, resulting in whats seen in the screenshots, instead of just applying the textures within the bounds of the pixels it does have. I having textures of different sizes and scales is useful for saving on file size, especially when custom models are involved.

**Screenshots**
![2023-06-09-21-29-32](https://github.com/Traben-0/Entity_Texture_Features/assets/3754909/88152bd1-9739-4c5f-8c69-57fb2218171a)

- If applicable, add screenshots to help explain your problem.

**Crash log**

- If the issue is a crash you **must** provide a crash log or nothing can be done.
- If it is not a crash your latest.log is always helpful to diagnose potential issues.
- https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report

**Your setup: (please complete the following information):**

- Minecraft version: 1.20/1.19.4
- ModLoader: Fabric 
- ETF Version [e.g. 4.0.1] 4.4.4 1.19.4 release and 4.4.4 1.20 pre 6 test
- Does the issue persist with only ETF installed? Yes it does
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? I had a look through open and closed bugs on github and didnt see mention of it

**Comment by Traben-0** [comment]
this pack uses custom chest models which are not fully supported by EMF yet but should be soon, and has nothing to do with ETF
