### ISSUE TITLE
[BUG] Personality mod incompatibility

### ISSUE THREAD

**Issue by LeKripiY** [Traben-0/Entity_Texture_Features#176]
So there's this mod by team abnormal named Personality which adds climbing animation, and keybinds for sitting and crawling. If your skin has an emissive texture, when you sit the emissive pixels will stay at their place and not follow the skin.

screens:
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/77859121/2a2b5764-352b-4ea6-9164-e348a7e59abe)

![image](https://github.com/Traben-0/Entity_Texture_Features/assets/77859121/71e38992-8acb-464f-98bc-82e10396bffe)

Setup:

- Minecraft Forge 1.19.2 - 43.2.8
- Forge
- ETF Version 4.4.4  ;  personality 1.19.2 3.0.1  ;  blueprint 1.19.2 6.1.2
- If ETF isn't installed there's nothing wrong while sitting

**Comment by Traben-0** [comment]
hmm, there is little i can do here, it seems this mod doesn't actually apply these animations to the player model or atleast reverts them quickly or is rendering a totally seperate model
I'm not sure why they'd be doing it that way, but any method that applies these changes to the model returned by "getModel()" in the LivingEntityRenderer for players should work fine for emissives if you want to tell the dev that
