### ISSUE TITLE
[BUG] crash on forge 46.0.10

### ISSUE THREAD

**Issue by ffuentesm** [Traben-0/Entity_Texture_Features#177]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**
New Forge version is incompatible with the mod

**Crash log**
https://pastebin.com/gFmtK8LW

**Your setup: (please complete the following information):**

- Minecraft version: 1.20
- ModLoader: Forge
- ETF Version 4.4.4
- - EMF Version: 0.2.10
- Does the issue persist with only ETF installed? if I remove both ETF and EMF it stops
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? yes

**Comment by Traben-0** [comment]
seems forge 46.0.10 broke something. 46.0.2 still works fine for me i will have an update out soon

**Comment by Traben-0** [comment]
this has been fixed in patch 4.4.5
