### ISSUE TITLE
[BUG] Crash on ETFManager init

### ISSUE THREAD

**Issue by Kevadroz** [Traben-0/Entity_Texture_Features#181]
**Describe the issue**

- What happened? Crashed on launch
- What were you doing when it happened? Loading the game

**Crash log**

[latest.log](https://mclo.gs/jkuaBJD)

**Your setup:**

- Minecraft version: 1.19.2
- ModLoader: Forge 43.2.14
- ETF Version 4.4.4
- Does the issue persist with only ETF installed? No
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? I have checked the Readme

**Comment by Traben-0** [comment]
resolved in version 4.5.0
