### ISSUE TITLE
[BUG] Physics mod cloth & Cape incompatibility

### ISSUE THREAD

**Issue by Fiopon** [Traben-0/Entity_Texture_Features#182]
**Describe the issue**

When using a cape that is not "Vanilla" with an ETF compatible skin, the Physics mod cloth physics disappear from the players cape, leaving only the vanilla cape.

**Screenshots**

https://github.com/Traben-0/Entity_Texture_Features/assets/56209751/0707c1dc-9311-436b-a9cc-b9001c1b7baf

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.1
- ModLoader: Quilt 0.19.1
- ETF Version 4.4.4
- Does the issue persist with only ETF installed? Yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? Yes

**Comment by Traben-0** [comment]
this will be fixed next version,
however emissive and enchanted pixels on capes will not work, i dont think support its even possible with how physics mod handles this

**Comment by Traben-0** [comment]
resolved in version 4.5.0
