### ISSUE TITLE
[BUG] Exceptions with some block model

### ISSUE THREAD

**Issue by Ba-Bao-zhou** [Traben-0/Entity_Texture_Features#184]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

- Exceptions with the block model
- Chest(not connected together)
- All the shulker box

**Screenshots**
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/92072976/90b7e454-1983-4d03-8b4f-0cb9ba3f335f)

**Crash log**

- If the issue is a crash you **must** provide a crash log or nothing can be done.
- If it is not a crash your latest.log is always helpful to diagnose potential issues.
- https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report

**Your setup: (please complete the following information):**

- Minecraft version:1.20
- ModLoader:Fabric
- ETF Version 4.4.4
- Does the issue persist with only ETF installed? Yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? Cant Connect to Discord

**描述问题**
-发生了什么？

-部分方块模型出现了些问题
-单个的箱子
-所有的潜影盒

-事情发生时你在做什么？[例如加载游戏、玩多人游戏、单人游戏]

-正常游戏(多人游戏和单人游戏都会出现这个问题)

**屏幕截图**
-如果适用，请添加屏幕截图以帮助解释您的问题。
**故障日志**
-如果问题是崩溃，您**必须**提供崩溃日志，否则将无能为力。
-如果不是崩溃，那么latest.log总是有助于诊断潜在问题。
-https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report
**您的设置：（请填写以下信息）：**
-Minecraft版本：1.20
-Mod加载器: Fabric
-ETF版本[例如4.0.1]：4.4.4
-仅安装ETF时问题是否持续存在？是
-你是否查看了Readme或Discord中的常见问题解答，看看它是否是已知问题？没法上Discord

**Comment by Traben-0** [comment]
I will need your resourcepack to test what is going wrong here

**Comment by Ba-Bao-zhou** [comment]
[彩虹像素RainbowPixel~☆v3.1.zip](https://github.com/Traben-0/Entity_Texture_Features/files/12160421/RainbowPixel.v3.1.zip)
[3D.Default.1.19.3.v1.6.0.zip](https://github.com/Traben-0/Entity_Texture_Features/files/12160427/3D.Default.1.19.3.v1.6.0.zip)
There should be the only ones that have changed the block model

**Comment by Traben-0** [comment]
this is actually an EMF issue and is already known, this will be part of the focus of the next EMF update

**Comment by Ba-Bao-zhou** [comment]
Thanks
