### ISSUE TITLE
Random texture feature doesn't work properly with biomes.#

### ISSUE THREAD

**Issue by NebulaGH** [Traben-0/Entity_Texture_Features#185]
For some reason, I can't have biome names labeled as _"CherryGrove"_ or _"SoulSandValley"_ and I have to have them written like **_"Cherry_Grove"_** and **_"Soul_Sand_Valley"_** the only reason why I see it as a problem it doesn't work like that for normal Optifine.

I tried seeing if it would work with ETF alone, without any biome name changes, and it made no difference.

Is there any thing I could do to not have to change the names for all of the biomes?

- Minecraft version: [1.20]
- ModLoader: [Fabric]
- ETF Version: [4.4.4]

**Comment by NebulaGH** [comment]
It did, thank you very much! <3

**Comment by NebulaGH** [comment]
alright, sounds good

**Comment by Traben-0** [comment]
resolved in version 4.5.0
