### ISSUE TITLE
1.19.2 - missing mixin property minversion

### ISSUE THREAD

**Issue by ColonelGerdauf** [Traben-0/Entity_Texture_Features#186]
`[17:15:13] [main/ERROR] [mixin/]: Mixin config entity_texture_features-forge.mixins.json does not specify "minVersion" property`
`[17:15:13] [main/ERROR] [mixin/]:</span> Mixin config entity_texture_features-common.mixins.json does not specify "minVersion" property`

These are what the logs are complaining about. It does not change much in gameplay, but it would clean up the log files a tiny bit. it being marked as an error will also frighten those not familiar with the logs or mixin errors.

**Comment by Traben-0** [comment]
added in commit 3c925f7

**Comment by ColonelGerdauf** [comment]
Will this be added in the 1.19.x builds?

**Comment by Traben-0** [comment]
Yes I actively develop the latest version then once I'm happy with the full update take all the changes and backport them at once

**Comment by Traben-0** [comment]
resolved in version 4.5.0
