### ISSUE TITLE
[BUG] Forge 1.20.1 crash on start

### ISSUE THREAD

**Issue by TenKotowsky** [Traben-0/Entity_Texture_Features#187]
I am using the newest version of ETF in my modpack for Forge 1.20.1. Whenever I try to start the game with the mod enabled it crashes. When I disable it, the game launches normally. Could be an incompatibility issue

Crash log:
https://gist.github.com/TenKotowsky/b91e126172a56570e6f8dbc237670f30

- Minecraft version: 1.20.1
- ModLoader: Forge
- ETF Version: 4.4.5
- Does the issue persist with only ETF installed? no
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? yes

**Comment by Traben-0** [comment]
resolved in version 4.5.0
