### ISSUE TITLE
[BUG] "incompatibility with 3D Skin Layers"

### ISSUE THREAD

**Issue by mamasch19** [Traben-0/Entity_Texture_Features#189]
**Describe the issue**

- emissive textures don't render on skin overlays (except for head overlay) with [3d skin layers](https://modrinth.com/mod/3dskinlayers) installed
- tested in singleplayer

**Screenshots**

- 3d skin layers installed: 
  ![on_front](https://github.com/Traben-0/Entity_Texture_Features/assets/51797687/505a439f-4e9a-4153-8839-5a7991783fa2) ![on_back](https://github.com/Traben-0/Entity_Texture_Features/assets/51797687/11b9f163-0587-4f14-a1b8-3f3ddec61fcb)
- 3d skin layers not installed: 
  ![off_front](https://github.com/Traben-0/Entity_Texture_Features/assets/51797687/73af00a2-990d-4a3b-bf65-95a1c6dfdfad) ![off_back](https://github.com/Traben-0/Entity_Texture_Features/assets/51797687/8a77fd28-d911-4bd5-95c1-673273a0f12e)

**My setup:**

- Minecraft version: 1.20.1
- ModLoader: Quilt 0.19.2 / Fabric 0.14.21 (tested both)
- ETF Version: [4.4.4](https://modrinth.com/mod/entitytexturefeatures/version/DpEWP7FH)
- 3d skin layers version: [1.5.4](https://modrinth.com/mod/3dskinlayers/version/M8d2bZuk)
- Issue persists with only ETF & 3d skin layers installed (without 3d skin layers it works as expected)
- not a known issue as far as I could tell

**Comment by Traben-0** [comment]
Is the 3d skin layers compatibility option enabled?

**Comment by mamasch19** [comment]
yes, that'S from the config file:
`"use3DSkinLayerPatch": true`

**Comment by Traben-0** [comment]
resolved in version 4.5.0
