### ISSUE TITLE
[BUG] "crashed with a modpack"

### ISSUE THREAD

**Issue by Thunderrock424242** [Traben-0/Entity_Texture_Features#190]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

- What happened? [e.g. crashed, texture is broken] it broke my modpack
- What were you doing when it happened? [e.g. loading the game, playing multiplayer, single-player] laoding the game

**Screenshots**

- If applicable, add screenshots to help explain your problem.

**Crash log**

- If the issue is a crash you **must** provide a crash log or nothing can be done.
- If it is not a crash your latest.log is always helpful to diagnose potential issues.
- https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report
[launcher_log.txt](https://github.com/Traben-0/Entity_Texture_Features/files/12140501/launcher_log.txt)

**Your setup: (please complete the following information):**

- Minecraft version: [e.g. 1.19.2] 1.20.1
- ModLoader: [e.g forge/fabric] forge 47.1.0
- ETF Version [e.g. 4.0.1]  4.4.5
- Does the issue persist with only ETF installed?
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?
[latest.log](https://github.com/Traben-0/Entity_Texture_Features/files/12140504/latest.log)
[crash-2023-07-23_20.57.04-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/12140506/crash-2023-07-23_20.57.04-client.txt)

**Comment by Thunderrock424242** [comment]
It didn't happen before so maybe it's a mod incompatibility

**Comment by Traben-0** [comment]
resolved in version 4.5.0
