### ISSUE TITLE
[SUGGESTION] Optifine Random Paintings

### ISSUE THREAD

**Issue by LcorpOfficial** [Traben-0/Entity_Texture_Features#191]
Describe your suggestion...

Using the optifine random texture method to add paintings does not seem to work as expected, and would allow for additional paintings to be added easily.

this array of files should result in "alban" being replaced at random when it's placed

![image](https://github.com/Traben-0/Entity_Texture_Features/assets/73314328/ee2709d9-27a1-401a-a598-cc08e889dc43)

Does another mod also do this?

Unsure.

Does OptiFine do this?
Yes, it should. See here:

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties#L24

**Comment by Traben-0** [comment]
resolved in version 4.5.0
