### ISSUE TITLE
[SUGGESTION] Player Skin Features should show up on Armorstand Heads

### ISSUE THREAD

**Issue by GhostIsBeHere** [Traben-0/Entity_Texture_Features#193]
My emissive and enchanted skin features are not applied to player heads when on armorstands, and I would like them to be! This is somewhat of an extension of #157, also concerning the player_head item.

I'd also like blinking to appear on heads, but I can think of why others might not like that lol
**Screenshot**
![2023-08-03_18 34 47](https://github.com/Traben-0/Entity_Texture_Features/assets/61166139/df704387-be7d-4151-9653-5f51e52029af)

**Comment by Traben-0** [comment]
Are they working when placed as blocks? I can't make it much in your screenshot

**Comment by GhostIsBeHere** [comment]
It works when placed as a block, but not when on an armorstand.

**Comment by Traben-0** [comment]
I will look into that, as for blinking it is not planned to be supported for the head block.

**Comment by Traben-0** [comment]
Just to be sure as well, can you confirm everything is the same with no other mods installed?

**Comment by GhostIsBeHere** [comment]
Ah, let me do that rn

**Comment by GhostIsBeHere** [comment]
> Just to be sure as well, can you confirm everything is the same with no other mods installed?

Yes, everything is the same

**Comment by Traben-0** [comment]
![2024-06-02_02 49 04](https://github.com/Traben-0/Entity_Texture_Features/assets/8456487/779a11a3-1f6e-4014-9071-3126bdc7393f)
works but requires later mc versions, likely due to issues with older iris or sodium builds and etf
