### ISSUE TITLE
entityRenderLayerOverride break emissive with Iris installed

### ISSUE THREAD

**Issue by SebSemos** [Traben-0/Entity_Texture_Features#194]
Bit of a weird one. 
About all in the title, Tried with tanslucent and translucent_cull, the emissive stuff is not working with Iris (with and without shaders). Work as intended in any other case 
Not sure if I should also open a ticket on Iris page?

![2023-08-06_07 12 24](https://github.com/Traben-0/Entity_Texture_Features/assets/89230340/af07038e-81d4-414c-87cf-5e7635e4b6b2)

Picture edit, Vanilla means only ETF installed :p 

**Your setup: (please complete the following information):**

- Minecraft version: [1.20.1]
- ModLoader: [Fabric]
- ETF Version [e.g. 4.4.99]
- Does the issue persist with only ETF installed? No
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? Yes

**Comment by Traben-0** [comment]
what emissive mdoe are you using? default , bright or compat?

**Comment by SebSemos** [comment]
Default. I made a quick test, compat doesn't work neither and bright make it flash if I stand still (emissive off if I move)

**Comment by Traben-0** [comment]
flashing makes it sound like the emissive fix settings might have been changed, can you set your ETF settings to default and tell me if it works

**Comment by SebSemos** [comment]
You mean the whole settings of etf? 

Just realising also I have Iris 1.6.4, should have tried with the newest version. But I'm on my way to bed, I give a shot to all that asap 

Good night :)

**Comment by Traben-0** [comment]
Yes set all of ETF to default

**Comment by SebSemos** [comment]
Hi, I just tested with ETF on default, and updated to lastest Iris/sodium... it does still the same as yesterday.

I have notice tho, the emissive works on the "hidden face" of the texture going spectate inside the mob shows it, if this can help:

![2023-08-06_07 12 24](https://github.com/Traben-0/Entity_Texture_Features/assets/89230340/de21aac3-93d0-4b63-af3f-6fbcd4d836fe)

**Comment by SebSemos** [comment]
Seems fine with latest version
