### ISSUE TITLE
[BUG] "Iron golem random texture doesn't work"

### ISSUE THREAD

**Issue by jeancrafteo** [Traben-0/Entity_Texture_Features#197]
**Describe the issue**

- Random textures with names broke on Iron Golem.
- When i rename one of this , doesn't change his texture, but any other entity does

![image](https://github.com/Traben-0/Entity_Texture_Features/assets/89709901/307b3fe0-e676-421f-ad84-ad9e2ee8b71e)

**Your setup: (please complete the following information):**

- Minecraft version:  1.20.1
- ModLoader: last one
- ETF Version Last one
- Does the issue persist with only ETF installed? Yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? yes

**Comment by Traben-0** [comment]
Can I see your properties file
