### ISSUE TITLE
[SUGGESTION] "Tweak Emissive Intensity"

### ISSUE THREAD

**Issue by bonkmaykrQ** [Traben-0/Entity_Texture_Features#200]
Describe your suggestion...
Allow emissive pixels to be tweaked in intensity using the alpha channel. i.e. "glowing eyes" shouldn't be fullbright but rather slightly lit

Does another mod also do this?
Not on a per skin basis.

Does OptiFine do this?
No.

**Comment by Traben-0** [comment]
this should technically already work like you expect, though it will not interact nicely with the bright render mode or with shaders while the emissive fix settings are enabled

**Comment by Traben-0** [comment]
This can also be approximated by darkening the emissive texture
