### ISSUE TITLE
[BUG] Rendering glitch when looking at JER trading menu

### ISSUE THREAD

**Issue by ffuentesm** [Traben-0/Entity_Texture_Features#201]
**Describe the issue**

When I check the trading menu from JER the rendering of the game stops. This means that things such as mobs, the player's hand, and any nonblock model turn invisible. 
I am not sure if this is an ETF or a JER issue, but this render glitch does not happen on other tabs that show villagers, nor does it happen to the wandering trader model. 
Without ETF and EMF the rendering works, the texture still missing, but the glitch does not happen. 

**Screenshots**

![image](https://github.com/Traben-0/Entity_Texture_Features/assets/44974827/2212ae26-94e9-4bf0-bbaf-8a0aa1dfcce0)
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/44974827/a5c40a29-0c81-4818-a568-5b343aaa525c)
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/44974827/1d0383d0-298f-43e3-8f8c-91b297d373c8)
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/44974827/ed3fd054-32e8-451c-95df-3cea7237f300)
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/44974827/4e389b96-2192-432e-b87d-dbfb3e390d2c)

**Crash log**

[latest.log](https://github.com/Traben-0/Entity_Texture_Features/files/12503240/latest.log)

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.1
- ModLoader: forge 47.1.3
- ETF Version 4.5.1

**Comment by Traben-0** [comment]
At a glance it seems like an issue with nbt trying to get read in a random model property, with those custom rendered villagers. 
Its likely something on etfs end not being null safe due to a value not usually being null in vanilla.

I'll look into it.

for now if you delete optifine/cem/villager.properties in FA they should all work again but you will lose the seperate villager sleeping animations

**Comment by Traben-0** [comment]
can i get a version of the log where the render fails

this one is the one where it works but no textures with an error java.io.FileNotFoundException: minecraft:textures/entity/villager/profession/none.png

**Comment by Traben-0** [comment]
specifically a log with ETF + EMF installed

**Comment by ffuentesm** [comment]
Here are the logs, both ETF and EMF are installed with FA, and both EMI trades and JER. 
For some reason, only the trading tab of JER causes the crash, while the EMI trades tab causes no such thing. 

Event log: https://paste.gg/p/anonymous/3c88c73d0789489db7212802a128624c
Latest Log: [latest.log](https://github.com/Traben-0/Entity_Texture_Features/files/13060017/latest.log)

**Comment by Traben-0** [comment]
if you are on 1.20.2 the dev build i posted in my discord should fix this

it's just 1.20.2 for the moment until i'm ready to release then itll backport

**Comment by Traben-0** [comment]
for the moment whatever emf model is trying to read villager nbt will cause this

any villager.properties file in optifine/cem using nbt will trigger this

**Comment by Traben-0** [comment]
fresh animations for instance does it

**Comment by ffuentesm** [comment]
Well, I am on 1.20.1, as most of the mods I play are not yet being ported, since 1.20.3 is coming out soon. So it will take a while to see them updated. 
This is really strange, since EMI Trades also have the villager skin rendered with FA, and has no glitch or crash. While JER one does cause the crash. 

As you can see, even JEP has no crash on the render. 
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/44974827/a44d24e5-49f2-4c1a-96e9-4a2ed9c3b5e2)

While just the JER tab causes the crash.
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/44974827/77c6fda5-b8e6-45f3-aeb7-ec9bbd1b1bb4)

 Also, I think I have the same crash type when having the Villager item from Easy Villagers in a storage slot. 
Crash: https://bytebin.lucko.me/170FYHTxi1
