### ISSUE TITLE
[BUG] Incompatible with Skin Textures mod

### ISSUE THREAD

**Issue by nc-z** [Traben-0/Entity_Texture_Features#202]
When I'm overriding my own skin using the Skin Textures mod (https://modrinth.com/mod/skin-textures), my skin's entity texture features (such as blinking) no longer work. The skin displays, but the player skin features don't function.

I just thought I'd report the issue in case it's useful to anyone.

- Minecraft version: 1.20.1
- ModLoader: quilt
- ETF Version 4.5.1, Skin Features version 2.0.0
- Does the issue persist with only ETF installed? no
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?
yes

**Comment by Traben-0** [comment]
i'll look into it but it's not a priority

**Comment by Traben-0** [comment]
closed due to duplicate
