### ISSUE TITLE
[1.20.1] Crash when opening Copper Barrel with Easy Villager inside and EMF and ETF is installed

### ISSUE THREAD

**Issue by ffuentesm** [Traben-0/Entity_Texture_Features#203]
The crash happened with the combination of Easy Villagers 1.20.1-1.0.12, Entity Model Features 0.RC.4, Entity Texture Features 4.5.1, and Expanded Storage 10.0.0-beta.3. 

When I open the UI of a copper Barrel, if I have a Villager in my inventory, the game crashes. 
That does not happen in vanilla Chests. 
If EMF and ETF are not installed the crash does not happen in the Copper Barrel. 
If EMF and ETF are installed and I open the copper barrel, and there is no Villager item in it, the crash does not happen.
If EMF and ETF are installed and I open a vanilla chest with a Villager item in it, the crash does not happen. 

I already reported this error to Easy Villagers, and they said the error was not from their mod.

Versions
    Minecraft version 1.20.1
    Forge 47.1.3
    Mod version 1.20.1-1.0.12

When I open the UI of the Expanded Storage, and I have an Easy Villager villager item in my inventory, and both EMF and ETF is installed the crash happens.
Here is the log of the Crash: https://crashy.net/246a24a2-3b05-446b-93dd-36814467fbe5?code=gFeL4j

**Comment by Traben-0** [comment]
this might be fixed in the 4.6 dev build on my discord, only released for 1.20.2 for the moment

I can't tell as your crash log link doesnt work but i recall it being this

**Comment by jinkhya** [comment]
Hello, I'm having the same issue so I had subscribed to this thread. Here is the crashlog : 
https://gist.github.com/jinkhya/57dd36517bf0ac099c8f4e2a2398eb88

Thank you for looking into this :)
Best regards,
Jin

**Comment by AdeptusAutumn** [comment]
Just tried the 4.6 build on Forge 47.1.3, Minecraft 1.20.1 with Fresh Animations
<img width="737" alt="image" src="https://github.com/Traben-0/Entity_Texture_Features/assets/16197997/b86d7080-99d4-4be8-910c-9c6bfa7f3a34">
No Crash!
