### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by knoxhack** [Traben-0/Entity_Texture_Features#204]
**Crash log**
[crash-2023-09-29_00.58.17-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/12776519/crash-2023-09-29_00.58.17-client.txt).

- Minecraft version: 1.20.1
- ModLoader: Forge
- ETF Version: entity_texture_features_forge_1.20-4.5.1

**Comment by Traben-0** [comment]
This is known I am working on it

**Comment by knoxhack** [comment]
awesome, thanks :)

**Comment by merasmus44** [comment]
was this ever fixed? because i'm having the exact same issue

**Comment by Traben-0** [comment]
It is technically already fixed on the 1.20.2 dev branch I'll have dev builds up soon in my discord

**Comment by merasmus44** [comment]
will it work on 1.20.1?

**Comment by Traben-0** [comment]
I fixed this and and all future similar Issues by rewriting a major part of the texture property code, so I've needed to make sure its stable

**Comment by Traben-0** [comment]
> will it work on 1.20.1?

I will release it for 1.20.1 yes,  but that branch's build won't work for it if you build it

**Comment by Ghost-chu** [comment]
> > will it work on 1.20.1?
> 
> I will release it for 1.20.1 yes, but that branch's build won't work for it if you build it

Can also reproduce on 1.20.2 version.

**Comment by Traben-0** [comment]
this should be fixed in the 4.6 dev build on my discord, only released for 1.20.2 for the moment
