### ISSUE TITLE
[BUG] ETF 4.5.1 crashing on 1.20.2

### ISSUE THREAD

**Issue by TechPro424** [Traben-0/Entity_Texture_Features#206]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

- What happened? Crashed, log: https://mclo.gs/ndw1b0W
- What were you doing when it happened? Launching the game

**Crash log**

Log: https://mclo.gs/ndw1b0W
Crash log: https://mclo.gs/OxjcOSI

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.2
- ModLoader: Fabric 0.14.23
- ETF Version 4.5.1
- Does the issue persist with only ETF installed? No
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? Checked Readme, not Discord

**Comment by mmodrow** [comment]
I can confirm this problem:
https://mclo.gs/n6q2Scp

Crash on boot of 1.20.2 regardless of installed shaders or resource packs, which instantly gets solved by uninstalling ETF & EMF

**Comment by Traben-0** [comment]
are you using ETF's 1.20.2 specific build? or its 1.20 build?

**Comment by Traben-0** [comment]
future uploads of the 1.20 builds will prevent loading in 1.20.2, they still allow loading attempts in future version as the last update was before 1.20.2 released
