### ISSUE TITLE
[BUG] ETF crashes on latest forge version for 1.20.2 aka 48.0.30

### ISSUE THREAD

**Issue by TheRealOutcast1001** [Traben-0/Entity_Texture_Features#209]
entity_texture_features_forge_1.20.2-4.5.1

Mod crashes whenever trying to load on any forge version past 48.0.13

I loaded the game, and before it loads completely, the game crashes, ive loaded the mod by its self and no other mods conflict with this one. 

**Crash log**
[crash-2023-10-21_15.18.10-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/13061632/crash-2023-10-21_15.18.10-client.txt)

**Your setup: (please complete the following information): all information present in crash log

- Minecraft version: [e.g. 1.19.2]
 1.20.2

- ModLoader: [e.g forge/fabric] 
Forge 48.0.30

- ETF Version [e.g. 4.0.1]
 1.20.2: 4.5.1

- Does the issue persist with only ETF installed? 
Yes

- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? 
Checked everywhere i could except discord, cannot access discord in my location

**Comment by Traben-0** [comment]
does this still happen with etf 5.0?

**Comment by TheRealOutcast1001** [comment]
I have not tested it yet, but i'll give it a try later, considering its
been months since i've played with that mod set list that i used, i
don't remember the specifics behind it.

**Comment by Traben-0** [comment]
stable for forge 1.20.2-48.1.0
