### ISSUE TITLE
[BUG] Fresh animation (Texturepack)

### ISSUE THREAD

**Issue by Vexonek** [Traben-0/Entity_Texture_Features#211]
**Describe the issue**

- Piglin head don't have eyes

**Screenshots**

![Zrzut ekranu 2023-10-30 191941](https://github.com/Traben-0/Entity_Texture_Features/assets/142011941/eb6208e1-1851-4b03-b737-ca62479e5367)

**Your setup: (please complete the following information):**

- Minecraft version: [e.g. 1.20.1]
- ModLoader: [e.g forge]
- ETF Version [e.g. 4.6]
- Does the issue persist with only ETF installed?-YES

**Comment by Traben-0** [comment]
What resource pack

**Comment by Vexonek** [comment]
Fresh Animation

**Comment by Traben-0** [comment]
I believe that is a fresh animations issue,  optifine should do the exact same thing

**Comment by Vexonek** [comment]
Thank you for information
