### ISSUE TITLE
[BUG] "boat texture is broken with Reimagined resourse pack"

### ISSUE THREAD

**Issue by kakashi1464** [Traben-0/Entity_Texture_Features#214]
**Describe the issue**

- What happened? boat texture is broken with Reimagined resourse pack
- What were you doing when it happened? playing single-player

**Screenshots**

![image](https://github.com/Traben-0/Entity_Texture_Features/assets/126709049/c59cbc3a-ff44-48d7-a375-2e8aaf2f2289)

**Debug log**

https://mclo.gs/hG8cESo

**Your setup: (please complete the following information):**

- Minecraft version: [1.20.1]
- ModLoader: [forge 47.1.3]
- ETF Version [4.6.1]
- Does the issue persist with only ETF installed? No
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? No

**Comment by Traben-0** [comment]
link the resource pack, does the boat have a custom model?

**Comment by kakashi1464** [comment]
Reimagened

**Comment by kakashi1464** [comment]
Sorry for the  wait

**Comment by kakashi1464** [comment]
oohh the  link

**Comment by kakashi1464** [comment]
https://modrinth.com/resourcepack/reimagined

**Comment by kakashi1464** [comment]
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/126709049/38081dc8-e997-407b-a56c-c12a72637b78)

this made it even worse

**Comment by kakashi1464** [comment]
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/126709049/9d2dcd40-5962-450a-ba39-46c670566173)
didn't help either

**Comment by Traben-0** [comment]
just putting this here for my future debugging of this issue

```[Render thread/WARN]: [Entity Model Features]: default model returned for minecraft:chest_boat/dark_oak#main due to exception: Cannot invoke "traben.entity_model_features.models.EMFModelPartWithState$EMFModelState.defaultTransform()" because "newState" is null```

**Comment by kakashi1464** [comment]
🤔

**Comment by Traben-0** [comment]
resolved for next update to emf

**Comment by kakashi1464** [comment]
![2024-01-23_15 32 52](https://github.com/Traben-0/Entity_Texture_Features/assets/126709049/47ab5d1c-1ac7-4a1d-be6f-a7400513836e)
![2024-01-23_15 32 53](https://github.com/Traben-0/Entity_Texture_Features/assets/126709049/4817cce3-f4f5-491c-ab0e-7349f45d8a7f)
bruh

**Comment by SkeleBones** [comment]
On the latest release of this mod and the latest version of Reimagined the chest boats do not do that, but I also see the standard boats rotating. This is while also having EMF. 
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/38815328/a2dd5369-71f6-4b39-b654-b8c1f2ff06af)


> ![2024-01-23_15 32 52](https://private-user-images.githubusercontent.com/126709049/298883471-47ab5d1c-1ac7-4a1d-be6f-a7400513836e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjE2MjEsIm5iZiI6MTcwOTgyMTMyMSwicGF0aCI6Ii8xMjY3MDkwNDkvMjk4ODgzNDcxLTQ3YWI1ZDFjLTFhYzctNGExZC1iZTZmLWE3NDAwNTEzODM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNDIyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjgzYjM4MzUyMTA2YWQ0MGY4Y2Q4MjU4MzgzYWRhMjQ0YWQ4MmJhODYyZDIyZTJmOTg5MDM2MmYxYTZkZGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pbPVpueXyh42Dl-rN7ALkx8VNqaHvR1TfLGCYYKHcv8) ![2024-01-23_15 32 53](https://private-user-images.githubusercontent.com/126709049/298883532-4817cce3-f4f5-491c-ab0e-7349f45d8a7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjE2MjEsIm5iZiI6MTcwOTgyMTMyMSwicGF0aCI6Ii8xMjY3MDkwNDkvMjk4ODgzNTMyLTQ4MTdjY2UzLWY0ZjUtNDkxYy1hYjBlLTczNDlmNDVkOGE3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNDIyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDg0M2NkYzljZWRlOTE4ODlhNjQ5YjMwZmFlYjA4ODU4MzFjNjE3MDJmNTE1YmZkOTE5MjNkMWJkOTE3OTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sHfkXzk_0BSRsB90SKyISo0naw7nZ6ie7huOYqJkA6w) bruh
