### ISSUE TITLE
[BUG] Player skin features are incompatible with Skin Swapper

### ISSUE THREAD

**Issue by Thrumptus** [Traben-0/Entity_Texture_Features#216]
Player skins with ETF features don't use them when selected with Skin Swapper

https://github.com/cobrasrock/Skin-Swapper 

- Minecraft version: 1.20.1
- ModLoader: Fabric
- ETF Version 4.5.1, Skin Swapper Version 3.1.4
- Does the issue persist with only ETF installed? No
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? Yes

**Comment by Traben-0** [comment]
has it worked on any prior versions?

**Comment by Thrumptus** [comment]
This was the first version I tried it on, just went back and tried version 2.4.1 for 1.18.1 but it didn't seem to work there either, through the launcher or skin swapper

**Comment by Traben-0** [comment]
This should work now, unless that mod applies the skins in a weird way, in which case I am not considering adding custom support for at this time
