### ISSUE TITLE
[BUG] "incompatibility with epic fight, etf version 4.6.1"

### ISSUE THREAD

**Issue by 1foxy2** [Traben-0/Entity_Texture_Features#217]
emissive pixels on the player's skin becomes transparent when activating battle mode

[**Screenshots**]

![2023-11-29_23 34 28](https://github.com/Traben-0/Entity_Texture_Features/assets/127777030/1b111671-bc6c-4ae1-9848-f31d6b47581f)
![2023-11-29_23 34 32](https://github.com/Traben-0/Entity_Texture_Features/assets/127777030/bfa4b28a-eaed-4710-b8c1-1ef85d6b2875)

**Your setup: (please complete the following information):**

- Minecraft version: 1.18.2
- ModLoader: Forge 40.2.14
- ETF Version: 4.6.1
- Does the issue persist with only ETF installed? if there is only epic figth and etf - yes. if only etf - no
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? yes

**Comment by Traben-0** [comment]
etf 5.0 might fix this, i will not look into this issue further until i have a 5.0+ version ported back to 1.18.2 to test

**Comment by Traben-0** [comment]
the transparency should be fixed, I am unsure if emisives will be able to work easily, but its possible they work now
