### ISSUE TITLE
[BUG]The Puzzle configuration interface is incorrect

### ISSUE THREAD

**Issue by fireboy637** [Traben-0/Entity_Texture_Features#218]
When I look at the configuration interface provided by Puzzle, the game crashes, even though I only load the Fabric API, Puzzle, and ETF.I didn't get into any single-player or multiplayer.

https://github.com/Traben-0/Entity_Texture_Features/assets/145782402/7f81fab0-7411-4db0-8de5-4e813de22fb3

[crash-2023-12-01_17.28.47-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/13523538/crash-2023-12-01_17.28.47-client.txt)

Minecraft version:1.20.1
ModLoader:fabric 0.14.25
ETF Version:4.6.1

**Comment by Traben-0** [comment]
Ah yeah that class changed location,  going to need to be fixed In puzzles end I'll do a pr for it if i get time
