### ISSUE TITLE
[BUG]minecraft snapschot 1.20.3 RC1

### ISSUE THREAD

**Issue by Giveratv** [Traben-0/Entity_Texture_Features#219]
i have problem loading screen is freeze red screen mojang

**Comment by Traben-0** [comment]
There is no 1.20.3 build yet , it will come soon

**Comment by Giveratv** [comment]
New problem 1.20.4 When I choose emissive textures, for example visible ore, it returns to the initial settings and the textures do not load.

**Comment by Traben-0** [comment]
etf does not do block emissives, you need continuity for that
