### ISSUE TITLE
[BUG] NullPointerException Crash When Rendering Player

### ISSUE THREAD

**Issue by Provismet** [Traben-0/Entity_Texture_Features#222]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

The Monumenta server has a custom resourcepack that makes use of ETF. When playing on this server, rendering a certain player caused a null pointer exception and crashed the game.

**Screenshots**

N/A.

**Crash log**

[crash-2023-12-12_14.05.50-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/13649104/crash-2023-12-12_14.05.50-client.txt)

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.1
- ModLoader: Fabric
- ETF Version 5.0
- Does the issue persist with only ETF installed? Impossible to check given the circumstance.
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? I have checked both.

**Comment by Traben-0** [comment]
I'll look into this, version 4.6.1 should hopefully be stable for you in the meantime

**Comment by Traben-0** [comment]
related to shoulder parrot entities, fixed in 5.1 - not yet released
