### ISSUE TITLE
[BUG] Null pointer crash for custom mob heads

### ISSUE THREAD

**Issue by PastaLaPasta** [Traben-0/Entity_Texture_Features#224]
**Describe the issue**

- When the item/inventory model of a mob head (I've been using Skeleton as an example) is rendered, the game instantly crashes.
- I have tried this with both a finished model from somebody else's pack and one I created in Blockbench and didn't edit what so ever.
- I have tried this while only keeping Entity Texture Features and Entity Model Features enabled.

**Crash log**
- Here is the error message thrown out by the launcher after the crash happens.

**Beginning**
The game crashed whilst rendering item
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1921.method_24296()" because "$$0" is null
**End**

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.1
- ModLoader: Quilt
- ETF Version: 5.0
- [Link to testing pack used, including Blockbench project file](https://drive.google.com/file/d/17Loll-JD_9Lk2jJTZJU7tFei5MQtyqVq/view?usp=sharing)

**Comment by Traben-0** [comment]
should be fixed in 5.1 - not yet released
