### ISSUE TITLE
[Suggestion] Variable textures based on entity health

### ISSUE THREAD

**Issue by EnderBC** [Traben-0/Entity_Texture_Features#225]
I'm the creator of the pack Torturable Healthbars, that uses a function that only optifine has right now, which is the ability to change the texture of a specific mob based on its health. 
I've noticed that many people have also asked me if ETF compatibility is possible, and I use it too, and I would really like it if it could be done, obviously if it can be done and if you would like to add it.

Thanks if you would like to add this feature, otherwise thanks anyway for taking your time to read

If the pack is needed, here's the link https://modrinth.com/resourcepack/torturable-healthbars , that has all the information needed and all the pictures of the mobs

**Comment by Traben-0** [comment]
thats already in etf

the pack should work if it uses optifine random texture properties

does it not work?

**Comment by EnderBC** [comment]
I tried and it doesn't seem to work, at least for me, unless it has been added in an update this week. It does use random texture properties

**Comment by Traben-0** [comment]
huh that is news to me, or i lost track of that, i'll look into fixing that

**Comment by EnderBC** [comment]
> This is a simple ETF fix, Fabric Skyboxes Interop had the same issue. Optifine supports properties with range matches <max>-<min>, but it's not mentioned anywhere in the documentation. It seems that the dev of Torturable Healthbars has only included this format of range matching, where as it seems ETF only supports <min>-<max> ranges at the moment.

Oh wow thanks a lot it works now!

**Comment by Traben-0** [comment]
fixed in 5.1
