### ISSUE TITLE
Puzzle crashing in 1.20.2 or earlier

### ISSUE THREAD

**Issue by fireboy637** [Traben-0/Entity_Texture_Features#226]
I see "fixed the ETF & EMF config screen getting faded black in recent versions" in the changelog of version 5.0 of the ETF,but it doesn't seem to be fixed, even though I've switched to the latest version.Still the same old issue, crashing when pulling down the Puzzle config screen.

[crash-2023-12-23_23.10.07-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/13759487/crash-2023-12-23_23.10.07-client.txt)

Minecraft version: 1.20.1
ModLoader: Fabric 0.15.3
ETF Version: 5.0

**Comment by Traben-0** [comment]
What?

That fix message has nothing to do with puzzle???

It is puzzles implementation that needs to be updated, I'll look into doing a pr to fix it after the holidays

**Comment by Traben-0** [comment]
puzzle has fixed it but they havent backported the fix :/

**Comment by Traben-0** [comment]
for now just add
    "entity_texture_features"

into the disabled integrations list of your puzzle config file `<MC_DIRECTORY>/config/puzzle.json`

example:
```"disabledIntegrations": [
    "another_mod",
    "entity_texture_features"
  ],```

**Comment by Traben-0** [comment]
I will mark this as resolved as the creator has a fix, but they only seem to push releases for the current version :/

I will leave this pinned on the issues page so other can see the setting to prevent this crash that i've written above
