### ISSUE TITLE
[BUG] "ETF error when clicking on edit skins"

### ISSUE THREAD

**Issue by Silver00177** [Traben-0/Entity_Texture_Features#227]
I clicked on edit skins and my game crashed with this error
[crash-2023-12-25_22.24.35-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/13766014/crash-2023-12-25_22.24.35-client.txt)
I don't know what's wrong, so I'm coming here

**Comment by Traben-0** [comment]
fixed for v5.1- unreleased

**Comment by Silver00177** [comment]
> Исправлено для версии 5.1 - Невыпущенная версия

I'll keep in mind
