### ISSUE TITLE
[BUG] Incompability with 3D Skin Layers 1.6.0 on 1.19.2

### ISSUE THREAD

**Issue by Maypul** [Traben-0/Entity_Texture_Features#230]
**Describe the issue**

3D Skin Layers released an update on 1.19.2 versioned 1.6.0 which is conflicting with ETF. I have reported to them here:
https://github.com/tr7zw/3d-Skin-Layers/issues/138
and they said it should be reported on your side so here is the report.

**Screenshots**

N/A

**Crash log**

N/A but here is the latest.log with error spam:
[errors.log](https://github.com/Traben-0/Entity_Texture_Features/files/13804567/errors.log)

**Your setup: (please complete the following information):**

- Minecraft version: 1.19.2
- ModLoader: Forge
- ETF Version: 4.6.1 (latest)
- Does the issue persist with only ETF installed?: Yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?: I do not use Discord.

**Comment by Traben-0** [comment]
I have a fix in the works on the 1.20.4 dev branch

**Comment by Traben-0** [comment]
fixed for 1.20+

1.19.2   1.19.4   1.18.2  fixes  will come later

**Comment by Qian-F** [comment]
Because of this incompatibility, the 1.19.2 forge ETF  has written nearly 800,000 lines in my logs. I hope it can be fixed as soon as possible because this is really terrifying.

**Comment by Traben-0** [comment]
It will be before Tuesday

**Comment by Traben-0** [comment]
For the time being you can use the previous 3d skin layers update

**Comment by Qian-F** [comment]
Any progress? I just want to know the progress and don't mean to push you.

**Comment by Traben-0** [comment]
All good, I had hoped to have it out by now however, my hard drive failed partway through last week so that put this update on hold, i've only just got my new replacement today so I hope to push the update in the next couple days

**Comment by Qian-F** [comment]
Thank you for your reply! Looking forward to your update!

**Comment by Maypul** [comment]
Seems to be fixed on 1.19.2, closing this issue. Thank you.
