### ISSUE TITLE
Game Crashes while switching through JEI mod pages

### ISSUE THREAD

**Issue by rraku** [Traben-0/Entity_Texture_Features#234]
**Issue Description**

- What happened? Minecraft crashed.
- What were you doing when it happened? Switching through the JEI mod Tabs. Always crashes on the same page.

**Screenshots**

![Screenshot 2024-01-03 160912](https://github.com/Traben-0/Entity_Texture_Features/assets/155559774/ca0ca2d0-157e-49a4-af21-07965fff3f61)

**Crash log**

[crash-2024-01-03_16.04.30-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/13820626/crash-2024-01-03_16.04.30-client.txt)

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.1
- ModLoader: Fabric
- ETF Version 5.1.2
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?: No.

**Comment by Traben-0** [comment]
addressed this for etf 5.2.1 and emf 1.2.2 not yet released

**Comment by rraku** [comment]
thank you!
