### ISSUE TITLE
[BUG] Endless Errors with 3D Skin Layers (1.18.2)

### ISSUE THREAD

**Issue by Y1rd** [Traben-0/Entity_Texture_Features#235]
**Describe the issue**

- Put the latest version of both mods in the same instance
- Attempt to launch the game
- Similar to #230

**Screenshots**
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/100542617/1efab459-7087-405c-a5cb-932d14d30af7)

**Crash log**
- https://hastebin.skyra.pw/furizeyoda.md

**Your setup: (please complete the following information):**

- Minecraft 1.18.2
- Forge 40.2.14
- ETF 1.1.0
- Does the issue persist with only ETF installed? Yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? No, but mentioned earlier this is similar to another issue but for a different version.

**Comment by Traben-0** [comment]
Just like #230 this will be fixed when the next etf update is released for 1.18.2 planned within the next 4-5 days.

For now the 1.20 latest version is fixed and you can also downgrade skin layers for now which is the devs recommendation
