### ISSUE TITLE
[BUG] Incompatibility with world and resource reloading with AzureLib Armor-based mods

### ISSUE THREAD

**Issue by Ampflower** [Traben-0/Entity_Texture_Features#236]
Mirroring AzureDoom/AzureLib-Armor#5 since I don't know who's causing this.

## Steps to reproduce
1. Install
   - Minecraft 1.20.1
   - Fabric or Quilt
   - AzureLib Armor 2.0.3
   - Wizards 1.0.4+1.20.1 or Paladins 1.0.4+1.20.1
   - Entity Texture Features 5.1.2 or 5.0
2. Load into world
3. Put wizard or crusader armour on an armour stand or other living entity
4. Reload
   - The world
   - A resource pack
   - The entire resource system (F3+T)

## Crash log

[A lot of crashlog.log](https://github.com/AzureDoom/AzureLib-Armor/files/13838520/A.lot.of.crashlog.log)

## Your setup: (please complete the following information):

- Minecraft version: 1.20.1
- ModLoader: Fabric & Quilt
- ETF Version 5.1.2
- Does the issue persist with only ETF installed? No, not applicable due to modded items involved.
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? I don't see any open issue here regarding this crash, nor in the FAQ.

**Comment by 2el222** [comment]
This crash can happen randomly without even reloading, and by just opening inventory while having a AzureLib armor equipped

**Comment by Traben-0** [comment]
#237
