### ISSUE TITLE
[BUG] "Crash with AzureLib and epic samurai"

### ISSUE THREAD

**Issue by 2el222** [Traben-0/Entity_Texture_Features#237]
Crash between ETF, AzureLib Armor and Epic Samurai mod

- Game randomly crashes, mostly when u try to open player inventory with any of the armors equipped

**Crash log**
[crash-2024-01-04_18.27.35-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/13848925/crash-2024-01-04_18.27.35-client.txt)

Log

[2024-01-04-3.log.gz](https://github.com/Traben-0/Entity_Texture_Features/files/13848938/2024-01-04-3.log.gz)

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.1
- ModLoader: Fabric
- ETF Version 1.2.1
- Does the issue persist with only ETF installed? No
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? I did, someone had similar issue, but different crash log

**Comment by Traben-0** [comment]
this was fixed a while back, not sure which version
