### ISSUE TITLE
[BUG] RPG series mod incompability (AzureLib)

### ISSUE THREAD

**Issue by Kaizuto** [Traben-0/Entity_Texture_Features#240]
**Describe the issue**

**Bug**(?): With ETF, the rpg series armor(s), including spellbladenext, can't be renderered properly when on worn by entity, causes crash on client when on server

**Log:**
Armor worn by player: https://mclo.gs/docR01f
Armor worn by armor stand: https://mclo.gs/dArdJUY

Steps to produce: 
1. Join server
2. Have a entity wear said armor
3. leave server
4. Join again
**or**
1. Join server
2. Have an entity wear said armor
3. tp somewhere 
4. leave server
5. Join again
6. tp to the entity's area

Quoting the AzureLib dev from discord:
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/83712471/2a38b096-b15e-491e-a98f-596bc9fec93b)

- Minecraft version:1.20.1
- ModLoader: Fabric
- ETF Version: 5.0

**Comment by Traben-0** [comment]
some changes are planned for how armor is handled by etf, this fix wont be next update but i will try and have a toggle for disabling armor with etf in the next update

**Comment by Kaizuto** [comment]
let me know when you dropped the update

**Comment by Traben-0** [comment]
there is a dev build in my discord now that should fix this and also has an option to disable armor features it should be out within the week on cf and modrinth etc.

**Comment by ZiLenTz** [comment]
Hope we get an update soon.
The game is quite plain without it.
