### ISSUE TITLE
[BUG] "Crash upon opening ender chest"

### ISSUE THREAD

**Issue by Liamgrayskull** [Traben-0/Entity_Texture_Features#241]
[crash-2024-01-14_19.12.12-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/13934455/crash-2024-01-14_19.12.12-client.txt)

Modded Server environment, crash on client upon opening a structure-generated ender chest

- 1.20.1
- Forge
- ETF 5.1.2

**Comment by Traben-0** [comment]
fixed for next update
