### ISSUE TITLE
[BUG] Skin Features Not Loading When Using ImmediatelyFast

### ISSUE THREAD

**Issue by JuceInUse** [Traben-0/Entity_Texture_Features#242]
When attempting to load the game using only the mods listed above, skin features (only emissives are being used by me) seem to disappear entirely. Attempted to work with the configs within ImmediatelyFast but couldn't find anything that changed this behavior. Interestingly, mob emissives seem to also break when using this mod. HOWEVER, vanilla emissives continue to work

**WITHOUT IMMEDIATELYFAST**
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/85078618/c348709e-b244-4c14-b172-9342370cecc6)
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/85078618/f297fd7e-cbfa-47c5-bc94-252b4e233312)
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/85078618/da6e2c43-06c1-43c3-b08d-d5b063922d0b)

**WITH IMMEDIATELYFAST**
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/85078618/0075fe2b-f0a5-4f24-87bd-794f8efb8ef7)
<img width="124" alt="image" src="https://github.com/Traben-0/Entity_Texture_Features/assets/85078618/b7938539-843b-4cf3-85c1-cba9095769b3">
<img width="190" alt="image" src="https://github.com/Traben-0/Entity_Texture_Features/assets/85078618/62d81490-81f1-4416-850b-fea5208d3d7d">

**NOTE:** Brighter Emissives are solely used for dramatic effect. Emissives continue to not work with default and compatible settings

**My Setup:**
- **Minecraft version:** 1.20.4
- **ModLoader:** Fabric
- **ETF Version:** v5.1.2 & Dev 5.2.1
- **ImmediatelyFast Version:** v1.2.8

**Comment by Traben-0** [comment]
was fixed a while back, and will be fixed again for the new IF update see #271
