### ISSUE TITLE
[BUG] Crash Walking In New World

### ISSUE THREAD

**Issue by lanwoodall423** [Traben-0/Entity_Texture_Features#245]
**Describe the issue**

- Loaded into new world. Walked up to a structure. Crash references oculus, ETF, and batched entity rendering

**Crash log**
[crash-2024-01-20_13.33.31-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/13998869/crash-2024-01-20_13.33.31-client.txt)
[latest.log](https://github.com/Traben-0/Entity_Texture_Features/files/13998875/latest.log)

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.1
- ModLoader: Forge
- ETF Version 5.2.1

**Comment by Traben-0** [comment]
does it still happen if you remove etf?
