### ISSUE TITLE
[BUG] Quark's Chest Variants missing textures, with double chests just straight up becoming invisible

### ISSUE THREAD

**Issue by Kooreh** [Traben-0/Entity_Texture_Features#250]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

The Chest variants in the mod 'quark' seems to glitch and have some missing textures in the upper part of the block, with double chests just straight up becoming invisible.
![2024-02-19_01 58 15](https://github.com/Traben-0/Entity_Texture_Features/assets/76446852/93780b0c-7b2c-40b3-a35e-6e14847d6e33)
![2024-02-19_01 58 23](https://github.com/Traben-0/Entity_Texture_Features/assets/76446852/0cd72828-dc5d-4bf7-b52c-caf8a1e20b7a)
![2024-02-19_01 58 30](https://github.com/Traben-0/Entity_Texture_Features/assets/76446852/3c5e768f-3ca3-44b7-af0f-d6f8cdac31f3)
![2024-02-19_01 58 33](https://github.com/Traben-0/Entity_Texture_Features/assets/76446852/a05fbb70-e89a-429e-9b77-6bad1f218ee2)

**Your setup: (please complete the following information):**

- Minecraft version: Forge 1.19.2
- ModLoader: Forge 1.19.2
- ETF Version 5.2.3
- Does the issue persist with only ETF installed?
- yes.

**Comment by Kooreh** [comment]
I did some workaround; and it seems like this happens when I use the chest reimagined resource pack.
The normal vanillla chest and ender chest works fine, only the chest variantss that are from the mod quark

**Comment by Traben-0** [comment]
closing in favour of tracking #258
