### ISSUE TITLE
[BUG] image is not allocated crash, even after the fix.

### ISSUE THREAD

**Issue by netcore10** [Traben-0/Entity_Texture_Features#252]
We are one version above the bugfix, but apparently it still exists.

**Describe the issue**

- What happened? [e.g. crashed, texture is broken]
- What were you doing when it happened? [e.g. loading the game, playing multiplayer, single-player]

**Screenshots**

- If applicable, add screenshots to help explain your problem.

**Crash log**
[crash-2024-02-21_18.02.53-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/14366424/crash-2024-02-21_18.02.53-client.txt)

- If the issue is a crash you **must** provide a crash log or nothing can be done.
- If it is not a crash your latest.log is always helpful to diagnose potential issues.
- https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.1
- ModLoader: quilt / fabric
- ETF Version 5.2.2
- Does the issue persist with only ETF installed? yes, i tested
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? yes.

**Comment by Traben-0** [comment]
Fixed more comprehensively already in 5.2.3
