### ISSUE TITLE
[SUGGESTION] "Support Custom Entity Textures based on tags a entity has"

### ISSUE THREAD

**Issue by CarJem** [Traben-0/Entity_Texture_Features#253]
random textures for mobs could be great, however I believe in variants that don't change every time I relog, and while using the uuid might be a good option if things are added or removed it will reset, I propose the ability like names and teams to set a texture based on an entity tag, this way modpack / datapack creators can make custom variants with unique textures without implementing a brand new mob.

**Does another mod also do this?**
not that I can recall

**Does OptiFine do this?**
not since the last time I checked

**Comment by Traben-0** [comment]
As thanos covered above, entity tag information is server side only and is not sent to clients. So there is nothing etf can do.

This problem extends to some other nbt data as well.
