### ISSUE TITLE
[SUGGESTION] Translation platform

### ISSUE THREAD

**Issue by Madis0** [Traben-0/Entity_Texture_Features#256]
Describe your suggestion...

With the newly redesigned mods that share a settings screen, it now more than ever makes sense to have a translation platform. My suggestion is Crowdin, which also has a FOSS plan, and you could have one project with different files per mod. Alternatives include Transifex, Weblate, OneSkyApp and more.

(also discussed with you on Discord, but posting here to keep track of this)

Does another mod also do this? Yes. Minecraft (official!), Minecraft Launcher, Forge, NeoForge, Fabric, Mod Menu, MultiMC etc already use Crowdin.

Does OptiFine do this? No 😞

**Comment by Traben-0** [comment]
Is there a tutorial specifically for setting it up for mc mod translations? i had a real quick try of crowdin after our chat but couldn't get it working by blindly fumbling about in their ui

**Comment by Madis0** [comment]
The simplest setup is just connecting the GitHub repo and ensuring the file paths and names are correct.
https://store.crowdin.com/github

Alternatively, you can use a custom plugin in your mod (which you already found)
https://fabricmc.net/wiki/tutorial:ext_lang

**Comment by Traben-0** [comment]
see https://github.com/Traben-0/Entity_Texture_Features/blob/ETF-Main/.github/Cloning_or_contributing.md#languages available from the link at the top of the readme

**Comment by Traben-0** [comment]
soecifically for references here i've added crowdin support which I can merge with a single button press as desired in IntelliJ via a plugin
