### ISSUE TITLE
What's this? A crash?

### ISSUE THREAD

**Issue by harl** [Traben-0/Entity_Texture_Features#26]
It's fine with ETF 2.5.6 (and Fabric API 0.48.0), but not with ETF 2.5.7 or ETF 2.5.9.

Got some crashes like this:
https://gist.github.com/harl/4bf60ed7b40d636130c94eec7b4f428c

Suspecting ETF or Fabric API because they're the last to have been updated.
Installed Not Enough Crashes to help me make some sense of the reports. (It didn't really help, though.)

Got these additional crashes (no shaders, ETF 2.5.9) and they seem to be slightly different from each other:
https://gist.github.com/harl/f3319b0252500ada8fee9e6ab0975a1e
https://gist.github.com/harl/dbec75b1f238a503f204d5a3de6a7cc9

And these (with shaders enabled):
https://gist.github.com/harl/6976fa3edd92e369e5a5388afab4e2eb
https://gist.github.com/harl/e34cba04ada217699412ae26b3ed7bca

(and with ETF 2.5.7)
https://gist.github.com/harl/717b6ade41362e6508a4ce8efe02549c

Suggestions?

**Comment by Traben-0** [comment]
are you per chance using a resourcepack with villagers having either random or custom textures, can you link whatever you are using it may help identify one of the crashes.

In the meantine keep using the last non beta release 2.5.6 while i look into this bug

**Comment by harl** [comment]
Thanks for looking into this.

I've been using this pack for a few days:
https://www.planetminecraft.com/texture-pack/misas-realistic-texture-pack/

As you can see from my comment on that page, there are possibly further oddities with that specific pack (which may or may not be related, I have no idea as I don't know the exact technicalities).

There was another texture pack I had used before this (with ETF 2.5.6 or maybe 2.4.4/5), but it seemed to have issues with connected textures, and I didn't know what I could do about that. (I'm probably missing yet another mod or two for that, as connected textures haven't really worked to my satisfaction since sometime after MC 1.16.x)
I think it was the free 32x version of the "Patrix Texture Pack".
I'm open to recommendations in these matters.

**Comment by Traben-0** [comment]
please try v2.5.10 uploaded to cursforge, it should fix this

**Comment by harl** [comment]
So far, it's looking good!
I've now run the game with v2.5.13 for a while, and otherwise the same mods, shader and texture packs.
It hasn't crashed again under the same circumstances.
Thanks ;)
