### ISSUE TITLE
[BUG] Glitch in the player's blink textures

### ISSUE THREAD

**Issue by seriousfreezing** [Traben-0/Entity_Texture_Features#262]
I was trying to use the player's blink animation and I then edited it the way it should be and then published it on my account, and even so, it's still buggy

**Screenshots**
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/66693072/8d126317-329c-4af8-92a6-c13c77f4160d)

**Your setup: (please complete the following information):**
- Minecraft: 1.20.4
- ModLoader: Fabric
- ETF 6.0
- Does the issue persist with only ETF installed? Yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? I think so

**Comment by Traben-0** [comment]
Odd, send the skin, what did you change before uploading?

**Comment by seriousfreezing** [comment]
![Resultado](https://github.com/Traben-0/Entity_Texture_Features/assets/66693072/65d58fdc-cdbd-4164-9cc4-4474f51da0af)
![ETF_player_skin_printout](https://github.com/Traben-0/Entity_Texture_Features/assets/66693072/a2ab138d-bce2-4fe6-893b-11274219a534)
That second one was the change I made so that the feature would supposedly work. But even before or after the change, the result is the same

**Comment by Matynns** [comment]
doesn't seem to work on my skin either. it seems like the mod keeps defaulting to no features on the skin and so turning it on in settings resets the features to their default textures

**Comment by Traben-0** [comment]
Quick question, are you two trying to use the fresh moves player animation blinking? Or the etf static texture blinking?

**Comment by seriousfreezing** [comment]
I was trying to use it via the ETF, but even taking out all the resource packs still doesn't change the result.

**Comment by Traben-0** [comment]
are you using https://modrinth.com/resourcepack/tras-fresh-player/versions ?

**Comment by seriousfreezing** [comment]
Yes, but this bug still occurs without this resourcepack

**Comment by Matynns** [comment]
I'm not using Fresh Moves, just ETF/EMF as they are in Fabulously Optimized for 1.20.5.

**Comment by Melone-guy** [comment]
i am having the same problem

**Comment by Traben-0** [comment]
the specific issue related to the first screenshot was resolved
