### ISSUE TITLE
[SUGGESTION] "Edit wiki information or put back capes"

### ISSUE THREAD

**Issue by YoannError404** [Traben-0/Entity_Texture_Features#263]
It would be nice to edit the skin wiki info to add a warning about capes, because since 5.0 the feature has been **removed** (I just created a skin and struggled for a LONG time before reading the whole changelog, and figure it out).

Or put back the functionality, which I find nice because many more people can see the cape (the "Capes" mod, used to display a lot of different capes, deactivates "minecraftcapes.net" capes by default). 🙂

 _that's a lot of capes..._

**Comment by YoannError404** [comment]
My Skin :
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/107496899/244d78b4-881c-4d4c-bcf9-7d4427c488fc)

**Comment by Traben-0** [comment]
Ah that should have been corrected I'll look into it, which cape mod are you referring?

It's somewhat unlikely I'll re add the capes but I might do it when I do some of the planned changes to the skin feature system

**Comment by YoannError404** [comment]
I'm referring to this mod https://www.modrinth.com/mod/capes, which is widely used (description: A Fabric and Forge mod that lets you use capes from Optifine, LabyMod, and the MinecraftCapes Mod), 
but by default only optifine cape are enabled

**Comment by YoannError404** [comment]
![image](https://github.com/Traben-0/Entity_Texture_Features/assets/107496899/fca2bae8-ad7e-4c17-8b0d-776b51fa5bcb)
Just an image of the cape
