### ISSUE TITLE
[BUG] "Minecraft crash"

### ISSUE THREAD

**Issue by KIRUYXAN** [Traben-0/Entity_Texture_Features#264]
**Describe the issue**

All versions of the mod above 5.2.3 crash for me

**Crash log**

[logs](https://mclo.gs/zSM5Ixe)

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.1
- ModLoader: fabric
- ETF Version: 6.0+
- Does the issue persist with only ETF installed? 
YES
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?
YES

**Comment by Traben-0** [comment]
delete your entity_texture_features.json  config file and try again with teh default settings

this seems like the illegalt path setting in ETF is interacting poorly with another mod

**Comment by KIRUYXAN** [comment]
Thank you all work now
