### ISSUE TITLE
Emissive on Elytras Overwritten by 3D skin layers

### ISSUE THREAD

**Issue by Lucipo** [Traben-0/Entity_Texture_Features#27]
![image](https://user-images.githubusercontent.com/36358294/159404934-0062963f-04cf-4f9e-a1e4-3ff52949971b.png)

Any Pixels on a skin's 2nd layer when using the Skin Layers 3D mod ( https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d )
will show over the emissive particles on an elytra, even when the elytra is infront of the secondary skin layer. 

Am Using latest version of fabric and both ETF and Skin Layers 3D on 1.18.1

**Comment by Traben-0** [comment]
i'll have a look into this but it likely would have to be left as a fix for the 3d-skin-layer dev, the emissives in ETF use the beaconBeam RenderLayer this improves support for transparent emmisive features and allows shaders to usually natively provide bloom etc as they would for a beacon's beam, so any change to that could be detrimental for ETF.

my guess is the dev has the 3d skin parts render over that rendering layer so he doesn't run into issues with distant beacon beams appearing above the skin

**Comment by Lucipo** [comment]
Alright, let me know if I should reach out to 3d-skin-layers devs when you know :)

**Comment by Traben-0** [comment]
yeah this will have to be a 3d skin layer mod issue, the emissive layer works fine with the vanilla playert model but the 3d parts render over it
