### ISSUE TITLE
Failed to render Villager due to incompatibility with Custom Entity Models mod.

### ISSUE THREAD

**Issue by unofficialreece** [Traben-0/Entity_Texture_Features#28]
This mod is incompatible with Custom Entity Models (CEM) v0.7.0.

Crash Report: https://bin.birdflop.com/tuzegisobi.yaml

I use v2.5.9 of this mod, which is latest to this date.

**Comment by unofficialreece** [comment]
The problem is fixed after I downgraded the Custom Entity Models to v2.5.6.

**Comment by Traben-0** [comment]
can i get the resourcepack you were using during the crash if any

**Comment by Traben-0** [comment]
can you try version 2.5.10 on cursforge and tell me if thats fixed for you

**Comment by Traben-0** [comment]
I will mark this as closed as others with the issue have said it is fixed now, please feel free to open a new issue if it still doesn't work for you :)
