### ISSUE TITLE
The shulker's head doesn't seem to have a custom texture applied.

### ISSUE THREAD

**Issue by wsesrdtf** [Traben-0/Entity_Texture_Features#29]
Entity Texture Features - [Fabric]

Only the shulker's shell is affected.

![2022-03-26_14 41 17](https://user-images.githubusercontent.com/101512862/160226543-6962a3bf-f209-4b88-8fe7-0955be526d64.png)

![2022-03-26_14 41 34](https://user-images.githubusercontent.com/101512862/160226546-111a69b7-7ddf-413a-9ded-f89b3d4d9e27.png)

![shulker2](https://user-images.githubusercontent.com/101512862/160226609-15ae2da7-ec70-4865-9a92-aa732fb14a5e.png)

1.18.2
Fabric
Sodium + Iris

**Comment by Traben-0** [comment]
should be fixed for beta 2.5.12 let me know if its still broken for you

**Comment by wsesrdtf** [comment]
https://drive.google.com/file/d/1fgDnr1TwxfPBA2j7OVRXmJwUCON8rCn_/view?usp=sharing

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'cem'!
Exit Code: -1

**Comment by wsesrdtf** [comment]
https://drive.google.com/file/d/1GpEY1P1z2-l-mw7DE9SAzssjeJV95qpp/view?usp=sharing

![Honeycam 2022-03-26 21-37-39](https://user-images.githubusercontent.com/101512862/160239801-9a9b4f99-03e9-47d0-8b7c-29219a8a14e2.gif)

**Comment by wsesrdtf** [comment]
2.5.13 works fine

**Comment by Traben-0** [comment]
yes a small bug was in 2.5.12 it was fixed shortly in 2.5.13 it didn't appear if you loaded a world without villagers hence why it slipped through
