### ISSUE TITLE
( question ) name.<n>=<name>

### ISSUE THREAD

**Issue by wsesrdtf** [Traben-0/Entity_Texture_Features#30]
I'm not sure about the name function.

![제목 없음](https://user-images.githubusercontent.com/101512862/160240987-d907345e-d317-4dc3-92b0-4079f3451fb1.png)

shulker.properties
skins.1=2
name.1=석탄(=Coal)

skins.2=1

According to my intention, only the shulker named 석탄 should use skin2.
But all shulkers use skin1~2 randomly.

How should I configure it to work as I intended?

**Comment by Traben-0** [comment]
I'm thinking there may be an inconsistency with non english characters, does it work if you use the english word "coal"?

**Comment by wsesrdtf** [comment]
No.. 
When I changed the name to English and checked it again, 
it was just that skin.1 and skin.2 acted randomly on all shulkers, 
whether their names were English or Korean.

**Comment by Traben-0** [comment]
can you try the latest beta V2.5.15 it may fix this

**Comment by Traben-0** [comment]
if it is still broken please try the last stable release version 2.5.6 if it doesn't work there then we have a different problem

**Comment by wsesrdtf** [comment]
It seems to be working fine now. 😆
Thanks for every update.
It's a pity that it only seems to recognize English...😰

**Comment by Traben-0** [comment]
Yeah i'm not to sure what would be up with that, it should work fine but might be impacted by however minecraft handles unicode. I'll look into it eventually but it is not a priority at the moment, as an alternative you can also change it's texture based on the block it's on or scoreboard team its in, that way you can use any name.

**Comment by wsesrdtf** [comment]
Thank you for the information.
I think you're a great engineer with nothing you can't do. 👍
