### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by wsesrdtf** [Traben-0/Entity_Texture_Features#32]
command
/summon minecraft:shulker ~ ~1 ~ {NoAI:1b, CustomName:'{"text":"X-ray"}', Color:15b}

(color:15b = black)

shulker.properties
skins.1=2
name.1=X-ray

skins.2=3
name.2=Crawl

skins.3=1

In this way, if color is attached to NBR, the name tracking random texture is not applied.
Is there any way to solve this?

**Comment by Traben-0** [comment]
i have fixed this for the 2.6.0 release later today

**Comment by wsesrdtf** [comment]
Thank you for always.

**Comment by wsesrdtf** [comment]
I don't know why, but with version 2.6.0 the memory usage increases to unlimited. 
Usually it stays at about 4GB, but in version 2.6.0, it increases by 1GB per second and uses up to the maximum of 32GB, and the game lags from that point on.

**Comment by Traben-0** [comment]
I've Replied in the separate issue you made for this :)
