### ISSUE TITLE
Question: Support for CIT armor emissives

### ISSUE THREAD

**Issue by maximumpower55** [Traben-0/Entity_Texture_Features#36]
Currently normal armor works with emissives but optifine CIT ones don't, is there any plans to add support for this?

Using [CITResewn](https://github.com/SHsuperCM/CITResewn)

~~Now that im writing this i realize i should have probably asked this in the discord~~

**Comment by Traben-0** [comment]
I will answer in dscord to but if CIT can pass their custom armour texture through the same process as my mod gets that texture as seen in the below link emissive will work for all CIT custom armours https://github.com/Traben-0/Entity_Texture_Features/blob/master/src/main/java/traben/entity_texture_features/mixin/client/entity/extras/MIX_ArmorFeatureRenderer.java

**Comment by Traben-0** [comment]
CIT has done this compatability before with elytras
