### ISSUE TITLE
Compatibility issue: fix fresh animation resource pack

### ISSUE THREAD

**Issue by EGOIST1372** [Traben-0/Entity_Texture_Features#37]
Please fix [fresh animation](https://www.curseforge.com/minecraft/texture-packs/fresh-animations) resource pack to work properly with sodium without need for Optifine/optifabric.

**Comment by Traben-0** [comment]
You need to submit this for the Custom Entity Model mod (CEM), my mod only does the emissive and random textures In that pack not the models, which work fine despite the broken models, see the first paragraph of the readme or the download  pages for mention of CEM being required for custom models.
