### ISSUE TITLE
Compatibility issue: fix cute mob models resource pack

### ISSUE THREAD

**Issue by EGOIST1372** [Traben-0/Entity_Texture_Features#38]
Please fix [cute mob models](https://www.curseforge.com/minecraft/texture-packs/cute-mob-models-resource-pack) resource pack to work with sodium without the need for Optifine/Optifabric.
Many mobs in this resource pack works flawlessly thanks to you <3 (if in CEM the "use model creation fix" is off models works good) but some models like strays, skeletons and zombie variants having spinning head problem and spiders feet are half buried under blocks.
I haven't checked all mobs but this 2 problems are the main ones.
Thanks in advance <3

**Comment by Traben-0** [comment]
You need to submit this for the Custom Entity Model mod (CEM) that does models, my mod only does the emissive and random textures In that pack, which work fine despite the broken models, see the first paragraph of the readme or the download  pages for mention of CEM being required for custom models and a link.
