### ISSUE TITLE
Compatibility issue: Fix better sheep and butterfly bats resource packs

### ISSUE THREAD

**Issue by EGOIST1372** [Traben-0/Entity_Texture_Features#39]
please fix [better sheep](https://www.curseforge.com/minecraft/texture-packs/better-sheep) and [butterfly bats](https://www.curseforge.com/minecraft/texture-packs/butterflies-bats) resource packs.
both resource pack works flawlessly but sheep head model looks a bit forward and bats that are not butterfly have one floating wing detached from their bodies.
everything else works great
also I made possible [better dogs](https://www.curseforge.com/minecraft/texture-packs/better-dogs) resource pack and all other resource packs of [Mrblueyeti](https://www.curseforge.com/members/mrblueyeti/followers) work with sodium by testing a set of mods and told the dev of resource pack to add your mod in that list since it was necessary to make it work

instructions:
Some base functions are slightly bugged but can be fixed using the following workaround:
To make the dog breeds appear in-game, press F3 + T after taming a wolf / giving a tamed wolf a supported name tag.

Required mods:
[Custom Entity Models (CEM)](https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem/files)

[Cloth Config API](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files)

[CompleteConfig](https://www.curseforge.com/minecraft/mc-mods/completeconfig/files)

[Entity Texture Features](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric/files)

[Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu/files)

[Puzzle](https://www.curseforge.com/minecraft/mc-mods/puzzle/files)

[Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files)

thanks <3

**Comment by Traben-0** [comment]
For the trouble you are having with wolves textures not updating yo need to have the same number of variations in the wild wolf as the tame for it to cary over without needing a reset, i think i will change this to be consistent with what you expected

As for the model problems You need to submit this for the Custom Entity Model mod (CEM) that does models, my mod only does the emissive and random textures In that pack, which work fine despite the broken models, see the first paragraph of the readme or the download  pages for mention of CEM being required for custom models and a link.
