### ISSUE TITLE
Compatibility with Animatica

### ISSUE THREAD

**Issue by SunnySlopes** [Traben-0/Entity_Texture_Features#43]
I use Animatica mod to take the place of OF's anim, while the blinking function in your mod would stop animatica from working, even when I turned off the blinking switch.

**Comment by Traben-0** [comment]
how does blinking stop animatica? is there a crash? if so can i see the crash log? does it happen with a particular resourcepack only?

**Comment by SunnySlopes** [comment]
Oh, sorry, it seems that there's something wrong with my texture pack. Anyway, thanks for your patience.
