### ISSUE TITLE
Incompatability with Figura

### ISSUE THREAD

**Issue by PencilVoid** [Traben-0/Entity_Texture_Features#44]
Refer to attached screenshots. ETF seems to cause the Figura player model to render independently of block light and only taking sky light into account, even if it doesn't have access to sky light. In the first image the model is rendering at full brightness despite the absurdly low block light and closed room since sky light is at full brightness. In the second and third images the model is rendering at dim brightness despite proximity to block light, since the sky light is low. I suspect the issue may be to do with emissive pixels, which my vanilla skin was set up to use through ETF. The vanilla player model has no such rendering issues, and thus isn't included in these screenshots. Tested with ETF version 2.6.0 and Figura version 0.0.8 on Minecraft 1.18.1.

![2022-04-12_17 13 53](https://user-images.githubusercontent.com/83508866/163454055-db527347-f1d0-4be4-8278-a44d0e316451.png)
![2022-04-12_17 14 12](https://user-images.githubusercontent.com/83508866/163454059-ef7f1935-be1b-454d-8a32-522c8c58f258.png)
![2022-04-12_17 14 47](https://user-images.githubusercontent.com/83508866/163454061-5ef4dbea-a5b1-4597-b1c8-d8825e959984.png)

**Comment by Traben-0** [comment]
does this still happen with skin feature disabled in the ETF config or mod menu settings?

I will look into this but I have the feeling I may just have to disable skin features if figura is present

**Comment by PencilVoid** [comment]
With player skin features disabled the Figura player model renders normally.

**Comment by Traben-0** [comment]
for now keep them disabled I will be looking into compatability

**Comment by PencilVoid** [comment]
This bug seems to be fixed in Figura's beta prereleases (versions 0.1.x).
