### ISSUE TITLE
Incompatibility issue with several emissive resource packs

### ISSUE THREAD

**Issue by EGOIST1372** [Traben-0/Entity_Texture_Features#45]
incompatible:(nothing glows)
[additional emissives](https://www.curseforge.com/minecraft/texture-packs/additional-emissives)
[emissive light glow](https://www.curseforge.com/minecraft/texture-packs/emissive-light-glow)
[emissive](https://www.curseforge.com/minecraft/texture-packs/emissive)
[radiant pack](https://www.curseforge.com/minecraft/texture-packs/radiant-pack)
[emissive-txf](https://www.curseforge.com/minecraft/texture-packs/emissive-txf)

**Comment by EGOIST1372** [comment]
this pack have only 3 mob (stray, piglin and zombified piglin) with glowing eyes and nothing more glows
[glows](https://www.curseforge.com/minecraft/texture-packs/glows)

**Comment by Traben-0** [comment]
ETF only applies glowing textures to entities/mobs, are there any entities/mobs not working in these packs or just blocks not working?

BTW the Continuity mod is working on an update to bring emissive blocks to fabric :)

**Comment by EGOIST1372** [comment]
I thought ETF supports for blocks as well, my bad
Thanks for the info <3
