### ISSUE TITLE
Bug with 3D models (CEM)

### ISSUE THREAD

**Issue by NovaXCIV** [Traben-0/Entity_Texture_Features#47]
I'm using Sodium + optionals & Custom Entity Models + Entity Texture Features. Version 1.18.2

Bug screen: https://imgur.com/a/CJz4P4g

Texture used: https://www.planetminecraft.com/texture-pack/the-doggos/

**Comment by NovaXCIV** [comment]
![image](https://user-images.githubusercontent.com/104044556/164212016-63f9a77a-7db6-4c82-9b74-605adfed412f.png)

**Comment by Traben-0** [comment]
We've discussed already over discord but this is a CEM issue :/
