### ISSUE TITLE
[1.18.2] Game crashed

### ISSUE THREAD

**Issue by pewblaze** [Traben-0/Entity_Texture_Features#49]
Playing on a Fabric 1.18.2 Server.
I used the mod "Vanish" before the crash (not sure if its related) a few times. After running a few steps the game crashed. (i was also stuck in a berry bush)
https://www.curseforge.com/minecraft/mc-mods/vanish

My log:
[latest.log](https://github.com/Traben-0/Entity_Texture_Features/files/8546638/latest.log)

**Comment by Traben-0** [comment]
i was never able to reproduce this, it seemed to be an issue with Xaeros minimap rendering, does this still happen for you in the latest version?
