### ISSUE TITLE
emissive elytra texture doesnt work when crouching

### ISSUE THREAD

**Issue by bennyd87708** [Traben-0/Entity_Texture_Features#50]
I saw that the only reason emissive elytras work at all is because they (kinda?) just worked out of the box with the CIT and everything else this mod already does so no biggie if it's too complicated to fix. I noticed that using an emissive elytra texture simply stops working if you crouch.  I tried every combination of the size fix and z fighting settings to no avail.
![2022-04-24_01 54 34](https://user-images.githubusercontent.com/6503310/164968744-5c134388-879f-419d-9760-55ab4882c864.png)
![2022-04-24_01 54 45](https://user-images.githubusercontent.com/6503310/164968745-18ec7c5e-05c0-4e3e-ba77-e879930509bb.png)

**Comment by Traben-0** [comment]
does this still happen with the 2.6.1 beta on curseforge?

**Comment by bennyd87708** [comment]
It looks like it might be fixed, but I can't really tell too well because the z-fighting fix option appears to be gone in that version so I can only see the emissive layer from odd off-angles in f5 mode.

https://user-images.githubusercontent.com/6503310/168697877-31ae93a1-4c24-44f7-b439-0f6f2dd3b00f.mp4

**Comment by RaptaG** [comment]
Isn't this fixed?

**Comment by Traben-0** [comment]
it has in a dev build not in stable

**Comment by Traben-0** [comment]
fix in V4.0
