### ISSUE TITLE
Client is crashing randomly

### ISSUE THREAD

**Issue by TheButterbrotMan** [Traben-0/Entity_Texture_Features#53]
https://bytebin.lucko.me/MjC9CYPcN3

**Comment by Traben-0** [comment]
does this still happen with no resourcepacks and with only ETF in the mod folder?
if it doesnt happen with only ETF installed then its might be an incompatability with another of your mods, hence why I need to know if it still crashes if it's the only mod :)

do any of those resourcepacks or mods affect skeletons? as that may be related to the crash

**Comment by pdoktor** [comment]
It's a mod incompat. As someone else who has many of the same mods you have, unfortunately it seems removing the heavier impact mob mods is the only fix as it just cannot keep up with memory.

**Comment by Traben-0** [comment]
what mods did you remove to alieviate the issue?

**Comment by pdoktor** [comment]
Removing really heavy impact mods like Mobz, Dimensional Doors, The Twilight Forest and/or Paradise Lost fixed the massive amounts of crashes for me. They all seem to cause significant crashes when trying to load the textures on entities/mobs just due to the amount of them rendered at a time.

**Comment by Traben-0** [comment]
I would love to see some of these crash logs, I can hopefully fix the underlying issue

**Comment by Traben-0** [comment]
are they the same as the first message here?

**Comment by pdoktor** [comment]
I'll attempt to replicate the error and edit this message if I do, but since your update I actually can't get the same error to replicate to a log. It simply crashes me in singleplayer when attempting to render items/entities with emissive textures, and will simply say "Server Closed"- sending me to the multiplayer screen. (Which tells me the internal single-player server is likely crashing)

**Comment by Traben-0** [comment]
thats good to here, I have also fixed the specific crash in the first comment in version 3.1.4 releasing tonight
