### ISSUE TITLE
Broken textures for some mobs when using Vanilla Additions

### ISSUE THREAD

**Issue by 0710H** [Traben-0/Entity_Texture_Features#54]
So far from what I have seen, the cows and the sheep textures are completely broken, but the random texture for every other modified mob still works.

![2022-05-15_14 45 13](https://user-images.githubusercontent.com/85057993/168460795-ade1b3e2-39d5-4d07-9456-095fe9a47fbe.png)

**Comment by Traben-0** [comment]
it looks like you are using a resourcepack that has custom mob models for these animals, you will need to try the CEM custom entity model mod to see if it can fix this
