### ISSUE TITLE
2 pixel blinking bugged

### ISSUE THREAD

**Issue by lxly9** [Traben-0/Entity_Texture_Features#55]
I can't for the life of me use 2 pixel blinking. I followed the step by step tutorial but the given skin and my own wont work. The 1 pixel blink works though.. I really dont get why this isnt working hm

**Comment by Traben-0** [comment]
can you provide your skin file that isn't working

**Comment by lxly9** [comment]
I am soo sorry, i managed to do it and it was because i didnt understand the wiki right. Again sorry i forgot to close the issue😭

**Comment by Traben-0** [comment]
:)
