### ISSUE TITLE
[Feature Request] Support different textures for the left and right wing of elytra

### ISSUE THREAD

**Issue by Sea-Kerman** [Traben-0/Entity_Texture_Features#57]
I was able to do this with JsonEM but then ETF can't put emissives on it, as discussed on the Discord
![2022-05-26_15 34 14](https://user-images.githubusercontent.com/41390862/170771275-31b2ad07-e562-4555-be21-2f025a249c49.png)

**Comment by Traben-0** [comment]
I actually saw you talking about this on the discord it is on my list

**Comment by Traben-0** [comment]
no eta yet
