### ISSUE TITLE
Emissive item textures don't work for custom models.

### ISSUE THREAD

**Issue by enjarai** [Traben-0/Entity_Texture_Features#61]
As said in the title, emissive item textures using a `_e` suffix don't work for items with custom models, where they do in OptiFine.

With OptiFine:
![image](https://user-images.githubusercontent.com/38552516/172021978-673e6ab4-9996-48e3-b7c7-f01189583286.png)

With ETF and CIT Resewn:
![image](https://user-images.githubusercontent.com/38552516/172021993-88fd8eab-4928-4c31-8853-723591f6decb.png)

**Comment by Traben-0** [comment]
you'll need the continuity m,od for emissive items, specifically the beta available on their discord
