### ISSUE TITLE
1.18.2 Forge Crash

### ISSUE THREAD

**Issue by Orgamorsh** [Traben-0/Entity_Texture_Features#64]
https://pastebin.com/hhXZ8Kih

**Comment by GoobyMain** [comment]
Me too.

V3.0.4
https://pastebin.com/7XUnKdJA

V3.1.2
https://pastebin.com/Q61pLSsc

**Comment by Traben-0** [comment]
i'm looking into this now

**Comment by Traben-0** [comment]
I have found the issue, cloth config is required on the forge version, and the game would crash before it could inform you of this.

V2.1.3 later tonight will fix the crash but cloth config api is still required
