### ISSUE TITLE
Ender chest texture broken (Fabric 1.19 latest version)

### ISSUE THREAD

**Issue by Lucipo** [Traben-0/Entity_Texture_Features#67]
Simple, ender chest is broken, if need more info because cannot replicate let me know

**Comment by Traben-0** [comment]
how is it broken, a screenshot perhaps?

**Comment by Lucipo** [comment]
![image](https://user-images.githubusercontent.com/36358294/174448442-7db4f766-1ef4-441a-ae17-651486252690.png)

https://pastebin.com/sddGeesV latest log for mod list and such

**Comment by pdoktor** [comment]
You have a resource pack conflicting with another. Re-organize them

**Comment by Lucipo** [comment]
I am using a vanilla installation (as in dot minecraft).

The ender chest issue doesnt happen with no resource pack, but using ONLY this pack (https://www.curseforge.com/minecraft/texture-packs/stay-true) breaks the texture.

**Comment by Traben-0** [comment]
it appears this is an issue with animated textures i'll have to look into this, i have an idea of the cause

**Comment by Traben-0** [comment]
the dev rewrite will fix thsi i will keep this open until it releases

**Comment by Julienraptor01** [comment]
i made a fixed pack for someone and i'll share it here
https://cdn.discordapp.com/attachments/988884456502865960/988916536339202098/Stay_True_1.18.zip

**Comment by Traben-0** [comment]
fix in V4.0
