### ISSUE TITLE
Sheep fur textures don't seem to be working

### ISSUE THREAD

**Issue by firyy** [Traben-0/Entity_Texture_Features#68]
I've been trying to add more sheep fur textures but all I get in game is the base white fur or sometimes the other base colours. I have both sheep.properties and sheep_fur.properties and everything named correctly, using the vanilla format in the texture files. Is this feature implemented?

**Comment by Traben-0** [comment]
it will be in the next update, i have no idea how this wasn't noticed for so long, you wont need a sheep_fur.properties it will match to the sheep and use default if it cant match

**Comment by Traben-0** [comment]
thisa has been fixed
