### ISSUE TITLE
Spiders are not textured correctly with Faithful Alternate entities

### ISSUE THREAD

**Issue by Lolothepro** [Traben-0/Entity_Texture_Features#69]
Spiders are not textured correctly with Faithful Alternate entities
![2022-06-16_13 47 15](https://user-images.githubusercontent.com/68275908/174063196-ba2ebda3-8737-456d-bbb8-280c58e33493.png)

**Comment by Traben-0** [comment]
the spiders in that pack use a custom model and the textures are shaped differently for this purpose try the CEM mod it can hopefully fix this, otherwise there is no way to make those textures fit the vanilla model

**Comment by Lolothepro** [comment]
CEM:
![2022-06-18_12 09 46](https://user-images.githubusercontent.com/68275908/174433157-de0b51ae-7c63-410d-9bdb-93c3abe0a63e.png)
