### ISSUE TITLE
Minecarts don't work at all

### ISSUE THREAD

**Issue by GoobyMain** [Traben-0/Entity_Texture_Features#70]
Random textures simply don't apply to minecarts.

I tried changing the texture of the minecart base and when I'd place one down it would only have the default texture.

What's weirder is I changed the texture of a chest, which worked when placed in world, but the texture of the chest in the chest minecart didn't change.

There is no chest minecart texture, the game uses a combination of both normal minecarts and normal chests

**Comment by GoobyMain** [comment]
I should note this is fabric V3.1.2 for minecraft 1.19

**Comment by Traben-0** [comment]
at the moment minecarts are not yet implimented, they will be in an update soon
