### ISSUE TITLE
Emissive trident doesn't work properly in emissive resource pack

### ISSUE THREAD

**Issue by EGOIST1372** [Traben-0/Entity_Texture_Features#71]
Emissive trident doesn't work properly in [emissive](https://www.curseforge.com/minecraft/texture-packs/emissive) resource pack.
It works when you hold it in hand but it stops glowing in item frame or when you drop it.
![image](https://user-images.githubusercontent.com/86555131/174295246-e04c45b3-9c1c-4d1c-81d2-39db0a888582.png)

**Comment by EGOIST1372** [comment]
also it seems you commented for that resource pack as well
![image](https://user-images.githubusercontent.com/86555131/174297388-0f035407-fc98-4201-8e21-bd3a28918832.png)

**Comment by Traben-0** [comment]
ETF only does the emissives and variations for the thrown and held trident entities, you will need the continuity mod's 2.0 update for emissive items and blocks.

ETF for entities and entity models & continuity for blocks and regular items, are both required for you have everything emissive

**Comment by EGOIST1372** [comment]
Oh ok but I already have continuity 2.0 for 1.19
So I need to report it in continuity's github right?

**Comment by PepperCode1** [comment]
While this isn't an ETF issue, I have helped Indigo and Indium resolve this, which will allow it to work correctly with Continuity. Fabric API 0.56.1 and Indium 1.0.6 for 1.18.2/1.19 contain the fix.
