### ISSUE TITLE
entity spawned on soul sand or mud use default texture when using the blocks rule

### ISSUE THREAD

**Issue by TheOnlyJoeEnderman** [Traben-0/Entity_Texture_Features#73]
I think it's because they spawn 1/16 a block above the block or something
![2022-06-19_11 58 06](https://user-images.githubusercontent.com/95948552/174492993-034fbb4e-bbbb-4ffc-aac1-f505648e7914.png)
![2022-06-19_12 14 06](https://user-images.githubusercontent.com/95948552/174492995-f015630c-615e-45fb-896a-cbe3492d711c.png)
![2022-06-19_12 14 12](https://user-images.githubusercontent.com/95948552/174492996-e474b545-f41c-4e0e-9f03-815b6d7fea41.png)
![2022-06-19_12 22 16](https://user-images.githubusercontent.com/95948552/174492997-80da7961-a0dd-4a83-a98f-8f4c6c3caa82.png)
?

I hope the images are helpful. I can copy and paste the properties file, but you can see everything else works. I set the texture to spawn on dirt for debug reasons.

**Comment by TheOnlyJoeEnderman** [comment]
This affects the latest two 1.19 releases of the mod. I haven't checked other versions.

**Comment by Traben-0** [comment]
this fix will be in version 3.1.4 tonight

**Comment by Traben-0** [comment]
the fixed version is uploaded now

**Comment by TheOnlyJoeEnderman** [comment]
Wow, that was fast.

**Comment by TheOnlyJoeEnderman** [comment]
Unfortunately the update did not fix the issue. I'll just work around that, since I don't need the block feature in this instance, biome will work fine. I can't think of any other times I'll need partial blocks for this feature.

**Comment by Traben-0** [comment]
strange I am sure it worked in my testing, i will try and get this working again

**Comment by TheOnlyJoeEnderman** [comment]
I can provide pictures or video, but it's literally doing the same thing as the older version. At first I thought I put the wrong version in my mods folder, so I checked the curseforge page and it was the same version.

I had a theory that any bugfix you made might make entities spawned on lily pads think they spawned on water. But that wouldn't be the case if the reason entites were showing the wrong texture was because of a bug in Vanilla. I don't know what the code is doing under there, so I could be completely wrong about what's happening.

**Comment by Traben-0** [comment]
what the code did was check the block directly below a mobs feet, this would round to the next lowest block if they were in a half/partial block like soulsand or lillies. I expanded the check to use the block its inside of too which would therefore count soulsand or lillies, I guess my testing was not thorough enough though, perhaps i spawned no ai mobs on the soulsand and they didn't fall into the partial block

**Comment by Traben-0** [comment]
i'll update when i have a fix out

**Comment by TheOnlyJoeEnderman** [comment]
Thanks

**Comment by Traben-0** [comment]
it was a small issue that was dependant on certain settings hence why it didn't affect my testing, it has been fixed in 4.0.beta.3 on curseforge, i will close this issue when its in a stable release

**Comment by Traben-0** [comment]
fix in V4.0
