### ISSUE TITLE
[Error] Could not execute entrypoint stage 'client' due to errors, provided by 'cem'!

### ISSUE THREAD

**Issue by Kino0208** [Traben-0/Entity_Texture_Features#77]
1.18.2 Fabric
use mods：
fabric-api-0.51.1+1.18.2
optifabric-1.13.0
OptiFine_1.18.2_HD_U_H7

cloth-config-6.2.57-fabric
ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric
PuzzlesLib-v3.3.5-1.18.2-Fabric

cem-0.7.1  ←[Error]
completeconfig-lib-1.4.1
entity-texture-features-3.1.4-mc1.18.x  ← [Crash Report]
modmenu-3.2.2

He doesn't seem to be compatible with Optifabric+Optifine
[latest.log](https://github.com/Traben-0/Entity_Texture_Features/files/8973965/latest.log)

**Comment by Traben-0** [comment]
optifabric does not, and likely never will, work with ETF as they partially do the same thing
