### ISSUE TITLE
[Forge 1.18.2] Crash (no other mod installed)

### ISSUE THREAD

**Issue by OverEarth12** [Traben-0/Entity_Texture_Features#78]
no other mod installed and when I tried run again for second time, it's respond different from first time I run.
when first run with mod installed:
[crash-2022-06-24_19.04.54-fml.txt](https://github.com/Traben-0/Entity_Texture_Features/files/8975981/crash-2022-06-24_19.04.54-fml.txt)
when tried run for second time:
[crash-2022-06-24_19.06.30-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/8975983/crash-2022-06-24_19.06.30-client.txt)

**Comment by Traben-0** [comment]
is cloth config installed?, it is supposed to notify you of the requirement but there has been an issue with it crashing before notifying of that

**Comment by OverEarth12** [comment]
> is cloth config installed?, it is supposed to notify you of the requirement but there has been an issue with it crashing before notifying of that

tried it with cloth config installed, turn out the same.

**Comment by Traben-0** [comment]
i'm aware of and looking into this issue

**Comment by Traben-0** [comment]
fix is up for version 3.1.5 for forge
