### ISSUE TITLE
Log Spam (Screenshot +Log included)

### ISSUE THREAD

**Issue by ardissaps** [Traben-0/Entity_Texture_Features#79]
Random texture spam that will keep [spamming indefinitely](https://paste.atlauncher.com/view/7583f243-5417-44d6-b53a-439fd04e72ac) until exiting world.
![image](https://user-images.githubusercontent.com/82106625/176326652-1fe6842f-d3b5-4db8-8b52-e6bc38c7dcca.png)

 I am **not** using [EBE](https://modrinth.com/mod/ebe) at all.

**Comment by ardissaps** [comment]
Disabled this function fixed problem :
![image](https://user-images.githubusercontent.com/82106625/176327151-bb5e39cf-42d8-4d1e-a7e6-e9f12b868394.png)

**Comment by Traben-0** [comment]
this will be fixed in the next stable release or dev build for now you can set the above mention setting to prevent this

**Comment by Traben-0** [comment]
fix in V4.0
