### ISSUE TITLE
[Forge] Crash with a clean .minecraft folder

### ISSUE THREAD

**Issue by ShipHeatRook** [Traben-0/Entity_Texture_Features#81]
I've been trying to get the mod to work on 1.18.2 (clean installation, no previous config files) and, after manually fixing in Java the issue that caused the mods.toml file to not being read properly, I still stumble upon this error.
Any way to fix it?
I'm using the 3.1.4 version of the mod.
![5](https://user-images.githubusercontent.com/52130730/176654866-970a3cd4-64ef-469f-8345-12395c351513.PNG)

**Comment by Traben-0** [comment]
#78

**Comment by Traben-0** [comment]
fix is up for version 3.1.5 for forge
