### ISSUE TITLE
Emissive textures bug

### ISSUE THREAD

**Issue by googlescientificnameforapig** [Traben-0/Entity_Texture_Features#82]
When you turn on "fullBrightEmissives" some emissive textures started becoming glitchy and transparent. Heres an example
![2022-07-08_19 42 17](https://user-images.githubusercontent.com/100143295/178083333-6723e0d0-28c7-4d26-9741-ba1cf80e6282.png) and also here is the pack:
[Emissivenetherite.zip](https://github.com/Traben-0/Entity_Texture_Features/files/9075541/Emissivenetherite.zip)

**Comment by Traben-0** [comment]
fix in V4.0
