### ISSUE TITLE
[1.19] [Fabric] Unwanted enchanted pixels on the cape

### ISSUE THREAD

**Issue by Precizne** [Traben-0/Entity_Texture_Features#84]
These 4 specific pixels(as per the screenshot) on the cape have enchantment glint on them even though that color isn't chosen in the skin file. Other pixels with the similar color do not have the glint on them. The pixels on the skin that are actually meant to have the glint are the eyes(which works). The eyes also use 2 tall blinking. This issue wasn't observed in 1.18.2 builds and only started with 1.19 builds. The cape type is minecraftcapes.net.
![2022-07-14_01 35 19](https://user-images.githubusercontent.com/63221503/178827403-e4124ddb-5c95-4e35-8811-b618aadd1651.png)
![2022-07-14_01 35 15](https://user-images.githubusercontent.com/63221503/178827419-09cddd88-8b63-4b95-9de2-f0999b0e2d03.png)

**Comment by Traben-0** [comment]
i have a suspicion, are those enchanted pixels the same shape as your eyes, i can't tell from your image, they may possibly be applying the skin enchanted overlay onto the cape accidentally.

Can you please tell me the exact ETF version as well please, is it a dev build?

**Comment by Precizne** [comment]
This was not happening in any 1.18 builds prior to the first 1.19 release. I have not checked any 1.18 builds after that as I updated to 1.19. I have observed it from the **first 3.1.0-1.19 version to the latest 3.1.4-1.19 version**. It also exists on **4.0-dev9**.

I also do think the enchanted overlay from the eyes are getting applied on the cape. Yes, they are the same shape as my eyes including the 2 pixel gap between the both (1 pixel on the edge and 1 pixel on the left of the enchanted pixels in the 2nd screenshot).

![2022-07-18_17 47 55](https://user-images.githubusercontent.com/63221503/179510179-77ffef53-19c5-44a9-8132-a5979a290d8f.png)
![2022-07-18_17 48 00](https://user-images.githubusercontent.com/63221503/179510186-c325d98e-f1ac-4fab-aa47-9991ef0170f3.png)

**Comment by Traben-0** [comment]
I've found the issue, was a small logic error accidentally using the base player skin instead of the cape texture for the enchanted check.
this will be in the next dev build on my discord, I will close this issue when it's on a stable build

**Comment by Traben-0** [comment]
fix in V4.0
