### ISSUE TITLE
[1.18.2] [fabric] incompatibility with more totems of undying

### ISSUE THREAD

**Issue by dadoirie** [Traben-0/Entity_Texture_Features#85]
it spams `[Render thread/ERROR]: shulker box custom rendering failed during setup, java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8503()" because "this.field_6002" is null` in the console when holding a shulker in the hand or searching it up in REI if having ETF installed with More Totems Of Undying

fabric 1.18.2
(note that only those two mods are enabled and the rest is disabled)
[https://mclo.gs/bH0qeUp](https://mclo.gs/bH0qeUp)

commented this on the more totems of undying curseforge page too as no idea which mod causes it

**Comment by Traben-0** [comment]
this spam has been fixed in 4.0

**Comment by dadoirie** [comment]
so not for 1.18.2?

**Comment by Traben-0** [comment]
a 1.18 version is on my discord for testing as it is a backport of the 1.19 version, it should be pretty stable and out on curseforge etc in a week or two

**Comment by Traben-0** [comment]
https://discord.gg/rURmwrzUcz  in the #devlog channel
