### ISSUE TITLE
[1.19] [V4.0.1] [Fabric] Shield emissive textures kills FPS.

### ISSUE THREAD

**Issue by kirmerk1** [Traben-0/Entity_Texture_Features#91]
When "Enable Optifine emissive entity textures" is "On" it reduces FPS depending on the number of resource packs enabled.
No resource packs: ~200FPS
5 resource packs: ~140FPS
25 resource packs: ~40FPS
Resource packs could be even for GUI only.
Long loadings are due to 1.19 bug. Also forgot to mute the mic, sorry.
https://www.youtube.com/watch?v=H5_l3cEk3Ns

**Comment by Traben-0** [comment]
are there any errors in the log? i have an idea of how i might be able to alleviate this

**Comment by kirmerk1** [comment]
[latest.log](https://github.com/Traben-0/Entity_Texture_Features/files/9233972/latest.log)
Removed unnecessary mods. 25 recource packs log.

**Comment by Traben-0** [comment]
[entity_texture_features_fabric-4.0.2.beta.1.zip](https://github.com/Traben-0/Entity_Texture_Features/files/9241825/entity_texture_features_fabric-4.0.2.beta.1.zip)
give this a go tell me if it helps

**Comment by kirmerk1** [comment]
Sadly no. FPS a little bit better. 65 instead of 40, but without "emissive entity" I still have 240
[latest.log](https://github.com/Traben-0/Entity_Texture_Features/files/9243366/latest.log)
.

**Comment by Traben-0** [comment]
i'm not getting the same kind of drop perhaps its the specific resourcepacks?
can you install the spark profiler mod https://spark.lucko.me/ and run  "/sparkc profiler" during the lag and after a few minutes run "/sparkc profiler --stop" it will give you a web url you can paste here and i can see exactly what code is causing the lag

also try this build
[entity_texture_features_fabric-4.0.2-GITHUBFIX.zip](https://github.com/Traben-0/Entity_Texture_Features/files/9247634/entity_texture_features_fabric-4.0.2-GITHUBFIX.zip)

**Comment by kirmerk1** [comment]
No changes with new build. https://spark.lucko.me/4MwWHAHRyp
Maybe you can reproduce it using the same map? https://www.planetminecraft.com/project/restworld-a-complete-resourcepack-testing-world-for-1-15-2/ Go to the shield/pattern room.

**Comment by Traben-0** [comment]
i will give it a go tomorrow, is it specifically the shield pattern room only where this happens?

**Comment by Traben-0** [comment]
does the issue go away if you disable shield emissive textures under special case emissive settings? perhaps it is a shield specific issue.

**Comment by kirmerk1** [comment]
Yes, it helps. I disabled shield emissive textures and everything works fine.

**Comment by Traben-0** [comment]
all good mate these things happen, i will investigate this shield issue :) explains why I couldn't reproduce

**Comment by Traben-0** [comment]
this should be greatly diminished in release 4.0.2 can you confirm?

**Comment by kirmerk1** [comment]
Everything works fine. Thank you.
