### ISSUE TITLE
The optifine texture of sheep fur does not work.

### ISSUE THREAD

**Issue by Dantigator** [Traben-0/Entity_Texture_Features#92]
I transfered my texture pack using this mod and the sheep with the image of body and fur can only load the body texture. The fur of the sheep dose not change but it works when I'm using optifine. Otherwise, the image I designed for cow in the flower forest is also not usable.

**Comment by Traben-0** [comment]
did you get it fixed?

**Comment by Dantigator** [comment]
yes, but i have an another problem on enderman and spider eyes.

**Comment by Traben-0** [comment]
what is the problem?
the discord may be of help https://discord.com/invite/rURmwrzUcz

**Comment by Dantigator** [comment]
Enderman eyes will return to default color when using BSL shader.
and it will become white without iris
![image](https://user-images.githubusercontent.com/71676400/182078709-ee9913de-837c-44d9-8243-5ed374d57f82.png)

**Comment by Traben-0** [comment]
i'm pretty sure thats a vanilla issue enermen eyes need to have the transparent parts be transparent AND black, if they are trnasparent AND white weird stuff can happen, and iris tends to fix those issues

**Comment by Traben-0** [comment]
try it without ETF
