### ISSUE TITLE
[Feature Request] NBT support for custom entity

### ISSUE THREAD

**Issue by Dantigator** [Traben-0/Entity_Texture_Features#94]
This is what I have always hoped to have before, just like CIT. Entity texture can be changed according to the NBT tags, like:
nbt.1=minecraft:goat {IsScreamingGoat:1} for screaming goat.
Is this possible? it dose not work with optifine though many people request, but i really need it.

**Comment by Traben-0** [comment]
this is planned, I have a big list of extra properties for all sorts of mobs i want to add including screaming goats, i have no ETA yet for these extra properties
