### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by Mahadbaloch** [Traben-0/Entity_Texture_Features#97]
Game crashes when trying to start immediately. Removing this mod fixed it. I have lots of mods and resource packs installed, but I didnt see any compatibility warning from fabric like I usually do.
[crash-2022-08-08_18.39.18-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/9282193/crash-2022-08-08_18.39.18-client.txt)
[crash-2022-08-08_18.39.16-server.txt](https://github.com/Traben-0/Entity_Texture_Features/files/9282194/crash-2022-08-08_18.39.16-server.txt)

**Comment by Traben-0** [comment]
etf is not compatible with Optifabric can you try without that, if it still persists please also check if the issue occurs when no other mods are installed

**Comment by Traben-0** [comment]
did you have any success?

**Comment by Mahadbaloch** [comment]
No I have optifabric installed so you were right
