### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Heartveiler** [Traben-0/Entity_Texture_Features#98]
https://bytebin.lucko.me/a9IvZMF1pj

**Comment by Traben-0** [comment]
duplicate of #93  there is a dev build on my discord that will release soon with a fix for this crash

**Comment by Traben-0** [comment]
you can find it on my discord already in the #devlog channel
it is versio 4.0.2.beta.3

**Comment by Heartveiler** [comment]
thank u
